.drone.yml, chat-server/.drone.yml, chat-server/.eslintrc.js, chat-server/environments/production.yml, chat-server/environments/staging.yml, chat-server/src/app.ts, chat-server/src/services/database.ts
Configuration of Drone pipeline for chat-server staging builds. Will configure prod builds as we get closer to go live. 
This will work for development purposes. 
Automatically pushes the server to staging env when a change is added to `main` branch.
=> (DOCSP-30565): Configure drone pipeline for `chat-server` staging

mongodb-atlas/.env.example, mongodb-atlas/.gitignore, mongodb-atlas/README.md, mongodb-atlas/add-search-index.ts, mongodb-atlas/package-lock.json, mongodb-atlas/package.json
Small script to generate Atlas Search Index with knnBeta (borrowed and slightly adopted from the MongoDB Oracle project)
Put in a MongoDB Atlas directory to have a centralized place for any other Atlas-related stuff we need to add. 
May want to build out this script/directory later with stuff like CI/CD, but this servers our purposes for the initial build out I think.
=> (DOCSP-30585): Generate search index script

chat-server/package-lock.json, chat-server/package.json, chat-server/src/app.ts, chat-server/src/routes/conversations/addMessageToConversation.ts, chat-server/src/routes/conversations/createConversation.ts, chat-server/src/routes/conversations/rateMessage.ts, chat-server/src/routes/conversations/utils.ts, chat-server/src/services/content.ts, chat-server/src/services/conversations.ts, chat-server/src/services/llm.ts, chat-server/src/utils.ts, chat-server/tests/routes/conversations.test.ts
Add non-streaming version of `POST /conversations/:messageId/messages/`. 
Note that I didn't implement some tests here in order to merge changes and get integrated with FE. Will return to tests in future work.
=> (DOCSP-30616): `POST /conversations/:conversationId/messages/` route, no streaming

chat-core/src/OpenAiEmbedFunc.test.ts, chat-core/src/OpenAiEmbedFunc.ts, ingest/src/commands/embed.ts, ingest/src/updateEmbeddedContent.ts
Jira: N/A
- When hitting the rate limit, use the recommendation in the message (if available) to determine backoff time.
- Run embeddings sequentially, as we're most likely to hit rate limit before any other performance bottleneck. This prevents overload of rate-limited requests and log spam.
- Increase attempt count to 25.
=> Add minor optimization for rate-limited embed requests

design_docs/db/atlas_search_index.jsonc, ingest/src/DevCenterDataSource.ts, ingest/src/updateEmbeddedContent.ts
Jira: N/A
- Adds logic to resume from where you left off in the embed command
- Also logs per-chunk so you have a better idea of why the rate limit is getting hit so often
Bits & bobs:
- Handle null entries in devcenter
- Update a spec document for new collection name
=> Add logic for ingest resumption

ingest/src/DevCenterDataSource.ts
Jira: N/A
Fixes the URL builder, which was copied from the Snooty side, but devcenter `calculated_slug` has a leading slash which, it turns out, overrides any path in the baseUrl.
=> Fix URL building for devcenter paths

chat-core/src/DatabaseConnection.ts, chat-core/src/Page.ts, ingest/src/IngestMetaStore.ts, ingest/src/commands/all.test.ts, ingest/src/commands/all.ts, ingest/src/commands/embed.ts, ingest/src/commands/pages.ts, ingest/src/updateEmbeddedContent.ts
Jira: https://jira.mongodb.org/browse/DOCSP-31304
- Creates 'all' command that can be run from docker, etc.
- Moves actual command logic to `doCommand` external functions so I can call them from elsewhere
- Uses a meta collection to keep track of previous successful runs - deducing this from existing documents turns out to be pretty complicated and we may as well just use a very early 'since' at that point: we would look at all pages and embeddings to make sure everything is successfully updated, then update those that have not yet been updated (the embed command does resume where it left off at least, so it wouldn't just duplicate work). That said, having a meta document in the database is a pretty simple optimization.
- Bug fix: warn and gracefully handle empty chunks set (which can …
=> (DOCSP-31304): Implement 'all' command

chat-server/.release-it.json, chat-ui/.release-it.json, ingest/.release-it.json, ingest/src/AcquitRequireMdOnGithubDataSource.test.ts, ingest/src/AcquitRequireMdOnGithubDataSource.ts, ingest/src/GitDataSource.test.ts, ingest/src/GitDataSource.ts, ingest/src/GitHubDataSource.test.ts, ingest/src/GitHubDataSource.ts, ingest/src/MdOnGithubDataSource.test.ts, ingest/src/RstOnGitHubDataSource.test.ts, ingest/src/SnootyProjectsInfo.test.ts, ingest/src/handleHtmlDocument.test.ts, ingest/src/handleHtmlDocument.ts, ingest/src/projectSources.ts, scripts/.release-it.json
Jira: none
- Uses makeGitDataSource as a drop-in replacement for GitHubRepoLoader.
- Langchain's GitHubRepoLoader consumes a lot of API requests and quickly hits the limit. This disrupts our tests. It's particularly annoying given that we only load public repos.
- Will probably need special work to handle private repos.
=> Replace GitHub data source

chat-server/src/processors/MongoDbUserQueryPreprocessorResponse.d.ts, chat-server/src/processors/QueryPreprocessorFunc.ts, chat-server/src/processors/makePreprocessMongoDbUserQuery.test.ts, chat-server/src/processors/makePreprocessMongoDbUserQuery.ts, chat-server/src/routes/conversations/addMessageToConversation.test.ts, chat-server/src/routes/conversations/addMessageToConversation.ts, chat-server/src/services/conversations.ts, scripts/src/scrubMessages.ts
Jira: none
- Adds "rejectQuery" field to preprocessor in order to avoid needing the DO_NOT_ANSWER thing
- Stores "rejectQuery" field in the database for future analysis
- The "rejectQuery" name was chosen over "doNotAnswer" to avoid confusion around double negatives
- Behavior change: previously, the bot would fail to answer if it couldn't rephrase. This would no longer be the case after this is merged. When a user pasted an error message, they got a DO_NOT_ANSWER because the bot couldn't rephrase it.
=> Do not fail query on rephrase fail

chat-server/src/app.test.ts, chat-server/src/config.ts, chat-server/src/routes/conversations/FindContentFunc.ts, chat-server/src/routes/conversations/addMessageToConversation.test.ts, chat-server/src/routes/conversations/addMessageToConversation.ts, chat-server/src/routes/conversations/conversationsRouter.test.ts, chat-server/src/routes/conversations/conversationsRouter.ts, chat-server/src/services/conversations.ts
Jira: none
- Increases code readability and enable further refactors by refactoring makeAddMessageToConversationRoute to centralize error handling under one catch block
- Simplifies implementation and improves extensibility by baking sprawled dependencies into a single injected `findContent` function
- Defines `findContent` in configuration
- TODO? Apply similar refactor principles to other paths
=> Conversations refactor

chat-ui/src/Message.tsx
Jira: (DOCSP-34007) [UI] Font size & spacing issues on live docs site
- Change message font size to 16
- Make sure that external stylesheets don't add margin to our message rating icons
=> (DOCSP-34007) [UI] Font size & spacing issues on live docs site

chat-server/src/app.ts, chat-server/src/llmQualitativeTests/generateChatTranscript.ts, chat-server/src/middleware/requestOrigin.test.ts, chat-server/src/middleware/requestOrigin.ts, chat-server/src/middleware/validateRequestSchema.ts, chat-server/src/routes/conversations/addMessageToConversation.test.ts, chat-server/src/routes/conversations/addMessageToConversation.ts, chat-server/src/routes/conversations/conversationsRouter.test.ts, chat-server/src/routes/conversations/conversationsRouter.ts, chat-server/src/routes/conversations/createConversation.test.ts, chat-server/src/routes/conversations/createConversation.ts, chat-server/src/routes/conversations/rateMessage.test.ts, chat-server/src/routes/conversations/utils.ts, chat-server/src/services/conversations.test.ts, chat-server/src/services/conversations.ts, chat-server/src/testHelpers.ts, design-docs/openapi.yml
Jira: (DOCSP-33030) [Q&A] Record request origin for usage tracking
- Requires and checks for the `Origin` HTTP header and saves it alongside every conversation & user message
=> (DOCSP-33030) [Q&A] Record request origin for usage tracking

docs/docs/index.md, docs/docusaurus.config.ts, docs/sidebars.ts
Jira: n/a
- Add WIP disclaimers to docs site
- Update sidebar/html `<title>` to list index page as "Home" to remove redundant "MongoDB RAG Framework"
-
=> Add WIP disclaimers + sidebar update to docs

packages/mongodb-chatbot-ui/src/Message.tsx
Jira: (EAI-219) [UI] Investigate responsive size on mobile
- Fixes message bubbles overflowing the edge of the window on small screen sizes
- Sets a fixed width for loading messages but not messages with text content
_Before_
_After_
=> (EAI-219) [UI] Investigate responsive size on mobile

packages/chatbot-server-mongodb-public/src/llmQualitativeTests/generateChatTranscript.test.ts, packages/chatbot-server-mongodb-public/src/test/testHelpers.ts, packages/mongodb-chatbot-server/src/app.test.ts, packages/mongodb-chatbot-server/src/routes/conversations/addMessageToConversation.test.ts, packages/mongodb-chatbot-server/src/routes/conversations/commentMessage.test.ts, packages/mongodb-chatbot-server/src/routes/conversations/conversationsRouter.test.ts, packages/mongodb-chatbot-server/src/routes/conversations/createConversation.test.ts, packages/mongodb-chatbot-server/src/routes/conversations/getConversation.test.ts, packages/mongodb-chatbot-server/src/routes/conversations/rateMessage.test.ts, packages/mongodb-chatbot-server/src/services/openAiChatLlm.test.ts, packages/mongodb-chatbot-server/src/test/testHelpers.ts, packages/scripts/environments/staging.yml
Jira: https://jira.mongodb.org/browse/EAI-33
- Moves test database creation and cleanup to beforeAll/afterAll hooks within the actual test helpers function
- Removes need for callers to drop database or close MongoClient
- This still won't clean up in the event of an aborted test run, so we should periodically run the cleanup script
=> (EAI-33): Move cleanup to testHelpers

packages/mongodb-chatbot-server/src/routes/conversations/getConversation.test.ts, packages/mongodb-chatbot-server/src/routes/conversations/getConversation.ts, packages/mongodb-chatbot-server/src/routes/conversations/utils.test.ts, packages/mongodb-chatbot-server/src/routes/conversations/utils.ts, packages/mongodb-chatbot-ui/src/ConversationProvider.tsx, packages/mongodb-chatbot-ui/src/services/conversations.test.ts, packages/mongodb-chatbot-ui/src/services/conversations.ts, packages/mongodb-chatbot-ui/src/useConversation.tsx
Jira: (EAI-226) [UI] Change Conversations without Reload
- UI
- `ConversationService`
- Adds support for the `getConversation` route
- `useConversation()` hook
- Adds a `switchConversation()` method to allow switching to a different, existing conversation by ID.
- Removes a check in `createConversation()` to allow starting a new conversation while one already exists.
- Server
- fix the get conversations routes so that it doesn't return the system message or non user/assistant response messages. 
- This is tough to test because we currently disable the `getConversations` route in our MongoDB server implementation via the [blockGetRequests middleware](https://github.com/mongodb/chatbot/blob/main/packages/chatbot-server-mongodb-public/src/middleware/blockGetRequests.ts).
- To test, you can …
=> (EAI-226) [UI] Change Conversations without Reload + [SERVER] get conversation route fix

package-lock.json, packages/mongodb-chatbot-eval/.eslintrc.js, packages/mongodb-chatbot-eval/.release-it.json, packages/mongodb-chatbot-eval/README.md, packages/mongodb-chatbot-eval/jest.config.json, packages/mongodb-chatbot-eval/package.json, packages/mongodb-chatbot-eval/src/CommandMetadataStore.ts, packages/mongodb-chatbot-eval/src/EvalConfig.ts, packages/mongodb-chatbot-eval/src/commands/evaluate.ts, packages/mongodb-chatbot-eval/src/commands/generate.ts, packages/mongodb-chatbot-eval/src/commands/report.ts, packages/mongodb-chatbot-eval/src/core.ts, packages/mongodb-chatbot-eval/src/evaluate/EvaluateQualityFunc.ts, packages/mongodb-chatbot-eval/src/evaluate/EvaluationStore.ts, packages/mongodb-chatbot-eval/src/generate/GenerateDataFunc.ts, packages/mongodb-chatbot-eval/src/generate/GeneratedDataStore.ts, packages/mongodb-chatbot-eval/src/generate/TestCase.ts, packages/mongodb-chatbot-eval/src/index.ts, packages/mongodb-chatbot-eval/src/main.ts, packages/mongodb-chatbot-eval/src/report/ReportEvalFunc.ts, packages/mongodb-chatbot-eval/src/report/ReportStore.ts, packages/mongodb-chatbot-eval/src/test/jestEnvSetUp.ts, packages/mongodb-chatbot-eval/src/test/jestSetUp.ts, packages/mongodb-chatbot-eval/src/withConfig.test.ts, packages/mongodb-chatbot-eval/src/withConfig.ts, packages/mongodb-chatbot-eval/testData/config/configTest.cjs, packages/mongodb-chatbot-eval/tsconfig.build.json, packages/mongodb-chatbot-eval/tsconfig.json
Jira: https://jira.mongodb.org/browse/EAI-232
Scaffold eval package with the following:
- Heavily based on set up from the ingest CLI
- I suspect some aspects of this will change as the project develops, but think useful to have this scaffold to build based off of.
=> (EAI-232):  Scaffold eval package

docs/docs/server/configure.md, docs/docs/server/rag/retrieve.md, examples/quick-start/packages/server/src/index.ts
Jira: n/a
- Add note about potentially having to change vector search minScore depending on embedding model used.
- Addresses feedback from https://github.com/mongodb/chatbot/issues/337
=> vector search `minScore` note

packages/mongodb-chatbot-ui/src/DevCenterChatbot.tsx, packages/mongodb-chatbot-ui/src/InputBarTrigger.tsx, packages/mongodb-chatbot-ui/src/MongoDbLegal.tsx, packages/mongodb-chatbot-ui/src/PoweredByAtlasVectorSearch.tsx, packages/mongodb-chatbot-ui/src/index.tsx
Jira: (EAI-265) Add Vector Search to chatbot disclaimer text
- Adds an export and additional rendering style for `PoweredByAtlasVectorSearch` text component
- Snooty PR implementing the same thing https://github.com/mongodb/snooty/pull/1040
=> (EAI-265) Add Vector Search to chatbot disclaimer text

package-lock.json, packages/mongodb-chatbot-server/package.json, packages/mongodb-chatbot-server/src/services/LangchainChatLlm.test.ts, packages/mongodb-chatbot-server/src/services/LangchainChatLlm.ts
Jira: n/a
- Modify langchain chatllm implementation to support Anthropic models
- i believe this change is compensating for a bug on langchain's side, as we were already conforming to their interface
- skipping test for anthropic b/c MongoDB doesn't have an Anthropic subscription that we could use in the integration test here. 
- You can sign up for free to anthropic and plug in your own API key (that's what i did)
- Thank you to @eric-gardyn for help with the solution implementation!
Resolves https://github.com/mongodb/chatbot/issues/382
=> `LangchainChatLlm` support for Anthropic

docs/docs/ingest/configuration-reference.md, package-lock.json, packages/mongodb-rag-core/package.json, packages/mongodb-rag-core/src/LangChainEmbedder.test.ts, packages/mongodb-rag-core/src/LangChainEmbedder.ts, packages/mongodb-rag-core/src/index.ts
Jira: n/a
- `makeLangChainEmbedder()` constructor of `Embedder` that wraps LangChain `Embeddings` class
- document `makeLangChainEmbedder()`
- the langchain `Embeddings` class has some nice support for things like retry and caching. we might want to consider migrating to using this instead of Azure OpenAI directly. 
- I want to add this before a hackathon on saturday so folks can use our framework w/ whatever embedding model they choose.
=> Support LangChain `Embeddings` class

packages/mongodb-chatbot-ui/src/useConversation.tsx
- For non-streaming responses, we were only rendering if there was metadata (i.e. if it was a verified message). Now this is fixed and we render all awaited messages.
=> fix: awaited, non-verified answers were not rendered

packages/ingest-mongodb-public/src/sources/MongoDbDotComDataSource.test.ts, packages/ingest-mongodb-public/src/sources/MongoDbDotComDataSource.ts
```
FAIL  src/sources/MongoDbDotComDataSource.test.ts (26.539 s)
● MongoDbDotComDataSource › should fetch pages
thrown: "Exceeded timeout of 5000 ms for a test.
Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."
13 | });
14 | describe("MongoDbDotComDataSource", () => {
> 15 |   it("should fetch pages", async () => {
|   ^
16 |     const pages = await dotcomDataSource.fetchPages();
17 |     // writeFileSync('pages.json', JSON.stringify(pages, null, 2))
18 |     expect(pages.length).toBeGreaterThan(0);
at src/sources/MongoDbDotComDataSource.test.ts:15:3
at Object.<anonymous> (src/sources/MongoDbDotComDataSource.test.ts:14:1)
```
- Adds a `limit` arg to the MongoDbDotCom data source
- Sets the `limit` …
=> Work around test that times out

packages/mongodb-rag-ingest/src/sources/snooty/SnootyProjectsInfo.test.ts
Looks like v4.4 isn't on the Snooty Data API anymore. This updates our test to use 6.0 which kicks the can a couple years down the road.
=> Fix test that used deprecated docs version

packages/mongodb-chatbot-ui/src/ChatWindow.tsx, packages/mongodb-chatbot-ui/src/ModalView.tsx
Jira: (EAI-343) [UI] Modal chat feed fills screen
- The modal will now take up to 70% of the user's viewport.
- On my MBP, this gives 170px more height to the chat feed.
- On my 4k 27" monitor this gives about 300px more height to the chat feed.
=> (EAI-343) [UI] Modal chat feed fills screen

packages/chatbot-eval-mongodb-public/environments/staging.yml, packages/ingest-mongodb-public/environments/production.yml, packages/ingest-mongodb-public/environments/staging.yml, packages/scripts/environments/production.yml, packages/scripts/environments/staging.yml
Jira: n/a
- Stop cronjob backoffs after 3 attempts
- should limit the amount of crashloopbackoff emails we get 🎉
=> cronjob stop backoff after 3

package-lock.json, packages/mongodb-chatbot-ui/package.json, packages/mongodb-chatbot-ui/src/ActionButtonTrigger.tsx, packages/mongodb-chatbot-ui/src/FloatingActionButtonTrigger.tsx, packages/mongodb-chatbot-ui/src/InputBarTrigger.tsx, packages/mongodb-chatbot-ui/src/index.tsx, packages/mongodb-chatbot-ui/src/useTextInputTrigger.ts
Jira: (EAI-457) [UI] Custom chatbot trigger helpers
- Refactors most of `InputBarTrigger` data and logic into a separate, re-usable hook
- Cleans up unnecessary `classnames` dependency in favor of Emotion's basically equivalent `cx`
- Makes it easier for devs to make input bar triggers like ours but with custom components/logic
- Most applicable use is for upcoming DOP work on a new trigger
=> (EAI-457) [UI] Custom chatbot trigger helpers

packages/mongodb-rag-ingest/src/sources/mongodb-university/makeUniversityPages.test.ts, packages/mongodb-rag-ingest/src/sources/mongodb-university/makeUniversityPages.ts
Jira: (EAI-461) University course content includes tags it shouldn't
- No longer includes tags from MDBU API
- Updates test
- Adds comments explaining why we don't do this
-
=> (EAI-461) University course content includes tags it shouldn't

packages/scripts/src/findFaq.ts
Jira: (EAI-472) FAQ Finder script is missing search filter
- Adds a default `filter = {}` for vector search to avoid the error breaking the script
=> (EAI-472) FAQ Finder script is missing search filter

packages/benchmarks/src/radiantModels.test.ts
Jira: n/a
- Skip loading env vars for benchmarks package radiant tests. they were causing test suite to fail.
-
- note that the tests are in fact passing despite the 🟡. issue w drone from yesterday makes it so webhook for green check (✅ ) never got called
=> env var skip fix

package-lock.json, packages/chatbot-eval-mongodb-public/package.json, packages/chatbot-eval-mongodb-public/src/braintrust/evaluateRagConversationsData.ts, packages/chatbot-eval-mongodb-public/src/braintrust/evaluateRagConversationsReferenceFree.ts, packages/chatbot-eval-mongodb-public/src/braintrust/utils.ts, packages/chatbot-server-mongodb-public/.env.example, packages/chatbot-server-mongodb-public/src/config.ts
Jira: https://jira.mongodb.org/browse/EAI-489
- Add script to do context-free RAG eval on model responses.
- For using GPT-4o mini as the main responder with GPT-3.5 for preprocessing
- The code to run braintrust here is fairly hacky. Once we have a evaluation vendor, we will create a more first-class integration between them and the evaluation CLI
- [Evals in braintrust](https://www.braintrust.dev/app/mdb-test/p/mongodb-chatbot-conversations/experiments/gpt-35-preprocessor-gpt4o-mini-responder-1724088921632?c=gpt-35-1724081121844&s=9d6628a7-e3f2-43c7-baa6-2aa203a1b553&diff=between_experiments&search={%22filter%22:[%22output%2520!%253D%2520%2522Unfortunately%252C%2520I%2520do%2520not%2520know%2520how%2520to%2520respond%2520to%2520your%2520message.%250A%250APlease%2520try%2520to%2520rephras …
=> (EAI-489): Braintrust-driven evals for adding new model

packages/chatbot-server-mongodb-public/environments/production.yml, packages/chatbot-server-mongodb-public/environments/staging.yml
Jira: n/a
- Adding missing K8s env var for using GPT-3.5 for preprocessor.
- 
- This should have been included in https://github.com/mongodb/chatbot/pull/475
=> Add missing env var for GPT-3.5 model

packages/chatbot-eval-mongodb-public/src/braintrust/evaluateRagConversationsData.ts, packages/chatbot-server-mongodb-public/environments/dev-rel.yml, packages/chatbot-server-mongodb-public/environments/production.yml, packages/chatbot-server-mongodb-public/environments/qa.yml, packages/chatbot-server-mongodb-public/environments/staging.yml, packages/chatbot-server-mongodb-public/src/systemPrompt.ts
Jira: https://jira.mongodb.org/browse/EAI-498
Based on the changes in #482, the production application is providing non-answers to too many questions b/c the exact answer isn't in the context information. This PR:
- Upgrades the main responder LLM from `gpt-4o-mini` to `gpt-4o`. 
- Updates the system prompt to allow greater freedom for the LLM to respond based on it's internal knowledge.
- We know that GPT-4o has much better internal knowledge of MongoDB based on our benchmarking of LLMs for MongoDB + much better general reasoning ability based on common benchmarks than GPT-3.5-turbo, our previous LLM, this should be a relatively safe move. While it might introduce some more hallucinations in various edge cases, it should have a net-positive effect.
- In k8s, pass models as non-secret env …
=> (EAI-498): Upgrade main responder LLM + system prompt to reduce AI non answers

package-lock.json, packages/mongodb-chatbot-evaluation/package.json, packages/mongodb-chatbot-evaluation/src/generate/generateLlmConversationData.test.ts, packages/mongodb-rag-core/package.json, packages/mongodb-rag-core/src/LangchainChatLlm.test.ts
Jira: (EAI-484) Fix broken langchain chat model wrapper
- Upgrade to the latest `@langchain/*` dependencies.
- Core wasn't actually referencing `@langchain/anthropic` as a dependency, so this adds that.
- Removes the `as unknown as` casts from https://github.com/mongodb/chatbot/pull/465#discussion_r1718834261
=> (EAI-484) Fix broken langchain chat model wrapper

packages/chatbot-server-mongodb-public/environments/production.yml, packages/chatbot-server-mongodb-public/environments/staging.yml
Jira: (EAI-447) Add Prometheus alerts for runtime server errors
- We should now get email alerts if the chatbot is responding 5XX to more than 2% of all requests in a 5 minute period
=> (EAI-447) Add Prometheus alerts for runtime server errors

docs/docs/quick-start.md
- Fix typo in quickstart guide to point to `http://localhost:3000/api/v1/conversations/`
- Add instructions for appending new messages to the conversation
- Example here uses `stream=false`, but users may want to use `stream=true` for longer responses
- Should note that the [default max input](https://github.com/mongodb/chatbot/blob/844bbf5e83ee8a7b6be1077c3b2407543429c0fb/packages/mongodb-chatbot-server/src/routes/conversations/addMessageToConversation.ts#L40) is 300 chars, which limits the types of inputs users can provide. Temporary workaround is to override by setting `maxInputLengthCharacters` in the example [config](https://github.com/mongodb/chatbot/blob/main/examples/quick-start/packages/server/src/index.ts#L125)
=> Update quick start guide documentation

packages/chatbot-server-mongodb-public/environments/staging.yml
Jira: (EAI-511) Add MDBU to allowed origins on staging
Adds the following staging origins for MDBU:
- https://learn-staging.mongodb.com
- https://mongodbcom-cdn.staging.corp.mongodb.com
=> (EAI-511) Add MDBU to allowed origins on staging

packages/chatbot-server-mongodb-public/src/config.ts, packages/chatbot-server-mongodb-public/src/processors/extractMongoDbMetadataFromUserMessage.eval.ts, packages/chatbot-server-mongodb-public/src/processors/makeStepBackRagGenerateUserPrompt.test.ts, packages/chatbot-server-mongodb-public/src/processors/makeStepBackRagGenerateUserPrompt.ts, packages/chatbot-server-mongodb-public/src/processors/userMessageMongoDbGuardrail.eval.ts
Jira: https://jira.mongodb.org/browse/EAI-518
- Allow for including more previous messages in the context. 
- We can do this now that we're using GPT-4o, which has a bigger context window.
- Fixed bug where we were passing the system prompt to the preprocessors. Validated that evals still run as expected w/o regression.
-
=> (EAI-518): Allow for more previous messages in context

packages/chatbot-server-mongodb-public/src/config.ts, packages/mongodb-chatbot-server/src/routes/conversations/addMessageToConversation.ts, packages/mongodb-chatbot-ui/src/App.tsx, packages/mongodb-chatbot-ui/src/Chatbot.tsx
Jira:
- https://jira.mongodb.org/browse/EAI-514
- https://jira.mongodb.org/browse/EAI-516
- Increase server default max input size to 3000
- Increase server implementation max input size to 3000
- Increase frontend default max input size to 3000
- Increase frontend implementation max input size to 3000
-
=> (EAI-514 & EAI-516): Increase default+implementation max input size to `3000`

packages/chatbot-server-mongodb-public/src/config.ts
Jira: https://jira.mongodb.org/browse/EAI-525
- Increase server LLM max output to `1000` tokens
- Since upgrading the main responder LLM to GPT-4o, the model tends toward giving longer responses, which are occasionally getting truncated. This change mitigates that problem.
=> (EAI-525): Increase server LLM max output to `1000` tokens

packages/chatbot-server-mongodb-public/src/config.ts
Jira: n/a
- Increased response timeout as part of the debugging of the main responder being slow.
-  As it turns out, the problem seemed to be due to transient issues with Azure OpenAI GPT-4o model.
- Still worth increasing as the generation can take longer now that we permit longer responnse from the model per #496 
-
=> Increase server chat response timeout to 60 seconds

packages/chatbot-server-mongodb-public/src/processors/userMessageMongoDbGuardrail.eval.ts, packages/chatbot-server-mongodb-public/src/processors/userMessageMongoDbGuardrail.ts
Jira: n/a
- we weren't doing a good job on a few AI related queries. this should widen the guardrails a bit further
- also, as part of the changes, there was a regression on the `$$ROOT` query. widened the guardrail on that to get it to a passing state as well. 
- Use `satisfies` instead of `as` for more semantic TS
- Eval https://www.braintrust.dev/app/mdb-test/p/user-message-guardrail/experiments/gpt-4o-mini-118dc962
=> Refine guardrail further 

packages/chatbot-server-mongodb-public/src/processors/makeMongoDbReferences.ts
Jira: (EAI-549) Don't assign a rich link badge based on mongodb-corp sourceName
=> (EAI-549) Don't assign a rich link badge based on mongodb-corp sourceName

packages/chatbot-server-mongodb-public/src/systemPrompt.ts
Jira: https://jira.mongodb.org/browse/EAI-551
- Change main responder system prompt to not include headers. 
- this causes 40% response length +generation time decrease vs baseline!
- braintrust eval: https://www.braintrust.dev/app/mdb-test/p/mongodb-chatbot-conversations/experiments/mongodb-chatbot-latest-7331e20f?c=mongodb-chatbot-latest&diff=between_experiments
=> (EAI-551): No headings in LLM responses

packages/mongodb-artifact-generator/src/withConfig.ts, packages/mongodb-chatbot-evaluation/src/withConfig.ts, packages/mongodb-rag-ingest/src/withConfig.ts
Jira: n/a
- now that we're compiling to `NodeNext`, we need to change how we import in the CLI w/ config packages. 
- fixes bug introduced in https://github.com/mongodb/chatbot/pull/548
-
- noticed in #543
=> fix exports for compiling to NodeNext

packages/chatbot-server-mongodb-public/src/eval/scorers/binaryNdcgAtK.test.ts, packages/chatbot-server-mongodb-public/src/eval/scorers/binaryNdcgAtK.ts
Jira: https://jira.mongodb.org/browse/EAI-604
- Fix NDCG metric
- Refactor NDCG for readability
- Make tests more precise w/ clearer names
- the problem was that the denominator of ideal DCG was being calculated incorrectly. it was including at most the actual number of correct documents in ideal order, but not the total number of possible documents. this kept the ideal number smaller, skewing the metric upwards.
=> (EAI-604): Fix NDCG metric

packages/chatbot-server-mongodb-public/evalCases/included_links_conversations.yml
Jira: n/a
- For evals that use the manual, fix the path from previous default `docs/manual/**/*` to `docs/current/**/*`
- This fixes retrieval evals that were failing with false negatives
-
=> Fix retrieval eval paths

package-lock.json, packages/mongodb-chatbot-ui/package.json, packages/mongodb-chatbot-ui/src/ChatMessageFeed.tsx, packages/mongodb-chatbot-ui/src/ChatWindow.tsx, packages/mongodb-chatbot-ui/src/ChatbotView.tsx, packages/mongodb-chatbot-ui/src/Message.tsx, packages/mongodb-chatbot-ui/src/MessageContent.tsx, packages/mongodb-chatbot-ui/src/MessagePrompts.tsx, packages/mongodb-chatbot-ui/src/MessageRating.tsx, packages/mongodb-chatbot-ui/src/ModalView.tsx, packages/mongodb-chatbot-ui/src/useChatbot.tsx, packages/mongodb-chatbot-ui/vite.config.component.ts
Jira: (EAI-598) [UI] Investigate further code splitting
- Adds some additional code splitting & lazy loading to some components inside of the chat window view
- Note the build output includes more, smaller, chunks. There is still some significant heft to the Message component that I think comes from the LG Chat markdown. Need to look upstream for a fix there.
Before (current `main`):
```
...
build/es/ConversationProvider.js            67.30 kB │ gzip:  16.89 kB
build/es/lodash.js                         121.75 kB │ gzip:  30.95 kB
build/es/index3.js                         173.01 kB │ gzip:  35.20 kB
build/es/index7.js                         181.52 kB │ gzip:  54.19 kB
build/es/messageLinks.js                   210.30 kB │ gzip:  41.70 kB
build/es/index2.js                         313.03 …
```
=> (EAI-598) [UI] Investigate further code splitting

package-lock.json, packages/mongodb-chatbot-ui/package.json, packages/mongodb-chatbot-ui/src/services/conversations.test.ts, packages/mongodb-chatbot-ui/src/services/conversations.ts, packages/mongodb-chatbot-ui/src/useConversation.tsx, packages/mongodb-chatbot-ui/src/utils.ts
Jira: (EAI-619) [UI] Make invalid stream event types a no-op
- We're now more relaxed if the server streams an SSE event that doesn't match our expectations. We used to throw, now we just log an error (in non-prod envs)
=> (EAI-619) [UI] Make invalid stream event types a no-op

package-lock.json, packages/mongodb-chatbot-ui/package.json, packages/mongodb-chatbot-ui/src/App.tsx, packages/mongodb-chatbot-ui/src/ChatbotView.tsx, packages/mongodb-chatbot-ui/src/DevCenterChatbot.tsx, packages/mongodb-chatbot-ui/src/createMessage.ts, packages/mongodb-chatbot-ui/src/messageLinks.test.ts, packages/mongodb-chatbot-ui/src/messageLinks.ts, packages/mongodb-chatbot-ui/src/references.test.ts, packages/mongodb-chatbot-ui/src/references.ts, packages/mongodb-chatbot-ui/src/services/conversations.test.ts, packages/mongodb-chatbot-ui/src/services/conversations.ts, packages/mongodb-chatbot-ui/src/useConversation.test.tsx, packages/mongodb-chatbot-ui/src/useConversation.tsx, packages/mongodb-chatbot-ui/src/verifiedAnswer.ts
For some arcane reasons, we can't import non-type symbols from core. We only use it minimally anyway, so this removes the dependency and copies the zod schemas from core into the UI package.
=> Remove mongodb-rag-core from UI package

package-lock.json, packages/benchmarks/package.json, packages/benchmarks/src/discovery/DiscoveryEval.ts, packages/benchmarks/src/makeOpenAiClientFactory.ts, packages/benchmarks/src/quizQuestions/QuizQuestionEval.ts, packages/benchmarks/src/quizQuestions/getQuizQuestionEvalCasesFromBraintrust.ts, packages/chatbot-server-mongodb-public/package.json, packages/chatbot-server-mongodb-public/src/config.ts, packages/chatbot-server-mongodb-public/src/conversations.eval.ts, packages/chatbot-server-mongodb-public/src/processors/retrieveRelevantContent.eval.ts, packages/mongodb-chatbot-server/src/routes/conversations/addMessageToConversation.ts, packages/mongodb-rag-core/package.json, packages/mongodb-rag-core/src/braintrust.ts
Jira: n/a
- Add `braintrust` as dependency to mongodb-rag-core, and use throughout project. doing this b/c we will need to integrate it with `mongodb-chatbot-server` for observability. this'll make 3 packages dependent on the library, so easier to maintain if we keep dependency centralized to core. 
-
-
=> Add braintrust to mongodb-rag-core

packages/mongodb-rag-core/src/contentStore/getChangedPages.ts, packages/mongodb-rag-core/src/contentStore/updatePages.ts
Jira: https://jira.mongodb.org/browse/EAI-158
- modified `logger.info` copy to provide a more descriptive message
- no code changes, works as intended
- this works as expected; I believe it looked buggy because the phrasing of the log message was unclear. 
From the JIRA ticket: 
> example of result that doesn't particularly make sense: 
```
{"level":"info","message":"wired-tiger had 159 in the store"}
{"level":"info","message":"After de-duplication based on page URL, have 159 unique old / 159 unique new pages"}
{"level":"info","message":"0 deleted / 0 created / 0 updated"}
```
> why  both 159 unique old and 159 unique new, for example? 
This is accurate. There were 159 documents in the store for `wired-tiger` before running the update. The data source `wired-tiger` has 159 urls to be …
=> (EAI-158): more descriptive logging for update pages command

packages/mongodb-rag-core/src/contentStore/MongoDbEmbeddedContentStore.test.ts, packages/mongodb-rag-core/src/contentStore/MongoDbPageStore.test.ts, packages/mongodb-rag-ingest/src/commands/all.test.ts
Jira: https://jira.mongodb.org/browse/EAI-655
In an attempt to fix flakiness,
- moved mongo memory server creation from beforeEach to beforeAll
- This should fix flakiness issues. If it does not, we can look into creating the mongo memory server globally
=> (EAI-655) fix mongo-memory-server test flakiness

packages/ingest-mongodb-public/package.json, packages/mongodb-rag-ingest/src/commands/embed.ts, packages/mongodb-rag-ingest/src/commands/pages.ts, packages/mongodb-rag-ingest/src/withConfig.ts
Jira: https://jira.mongodb.org/browse/EAI-614
- init added to ingest:pages
- init added to ingest:embed
- init calls removed from withConfig function
- I modified the npm commands for `ingest:pages` and `ingest:embed` to be able to run this locally. I can remove this, but leaving it in for now so that I remember to address it. It might make sense to set up `ingest:<pages|embed>:update` if we need a one liner for the update action, and have `ingest:<pages|embed>` set up to accept actions. I could use some context on when these commands are called before making that decision.
=> (EAI-614) add init action to ingest:pages and ingest:embed options

packages/mongodb-chatbot-ui/src/InputBarTrigger.tsx, packages/mongodb-chatbot-ui/src/conversationStore.ts, packages/mongodb-chatbot-ui/src/services/conversations.test.ts, packages/mongodb-chatbot-ui/src/services/conversations.ts, packages/mongodb-chatbot-ui/src/useChatbot.tsx, packages/mongodb-chatbot-ui/src/useConversation.tsx, packages/mongodb-chatbot-ui/src/utils.test.ts, packages/mongodb-chatbot-ui/src/utils.ts
Jira: (EAI-571) [UI] Support creating conversation on first message
- No more calls to `createConversation` - instead we always create the conversation on the first message
- Works locally with both streaming and awaited responses
- We never really counted "raw interactions" anyway, but this notably will make it so our db doesn't track if someone opens that chatbot but doesn't send a message.
=> (EAI-571) [UI] Support creating conversation on first message

packages/benchmarks/src/textToDriver/executeGeneratedDriverCode.test.ts, packages/benchmarks/src/textToDriver/generateDriverCode/makeGenerateDriverCode.test.ts
Jira: n/a
- Rename the DBs in the benchmarking suite to fix potential race condition with reading/writing to collections that'd been causing CI failures (see https://drone.corp.mongodb.com/mongodb/chatbot/4411/1/2)
-
-
=> Fix race condition in CI

.drone.yml, ingest-service.dockerfile, package-lock.json, packages/ingest-mongodb-public/package.json, packages/ingest-mongodb-public/src/sources/index.ts, packages/ingest-mongodb-public/src/sources/mongodbDotCom/WebDataSource.test.ts, packages/ingest-mongodb-public/src/sources/mongodbDotCom/WebDataSource.ts, packages/ingest-mongodb-public/src/sources/mongodbDotCom/webSources.ts
Jira: https://jira.mongodb.org/browse/EAI-639
- use playwright instead of puppeteer b/c easier to use in docker env
- use node:18 img instead of node:18-alpine b/c of issues w/ chromium in alpine
- note that this is the same as our CI tests
-
=> EAI-639: Working scraping with playwright

package-lock.json, packages/benchmarks/.gitignore, packages/benchmarks/package.json, packages/benchmarks/src/models.ts, packages/benchmarks/src/quizQuestions/QuizQuestionData.ts, packages/benchmarks/src/quizQuestions/QuizQuestionEval.ts, packages/benchmarks/src/quizQuestions/getQuizQuestionEvalCasesFromBraintrust.ts, packages/benchmarks/src/quizQuestions/makeHelmQuizQuestionPrompt.test.ts, packages/benchmarks/src/quizQuestions/makeHelmQuizQuestionPrompt.ts, packages/benchmarks/src/quizQuestions/mongoDbUniversityBadgeQuestionBenchmark.ts, packages/benchmarks/src/quizQuestions/mongodbUniversityAllQuestionBenchmark.ts, packages/benchmarks/src/quizQuestions/scripts/annotateBraintrustQuestions.ts, packages/benchmarks/src/quizQuestions/scripts/countQuestionsByTag.ts, packages/benchmarks/src/quizQuestions/scripts/loadBadgeQuizQuestions.ts, packages/benchmarks/src/quizQuestions/scripts/makeTags.ts, packages/chatbot-server-mongodb-public/src/lib.ts
Jira: https://jira.mongodb.org/browse/EAI-861
- Add Badge questions to Braintrust
- New benchmark for badge questions on all models
- Benchmark for badge+quiz questions on select models (requested by Chris for presentation to execs)
- [Braintrust experiments](https://www.braintrust.dev/app/mdb-test/p/mongodb-multiple-choice/experiments?y=score|CorrectQuizAnswer&ye=metric|duration,metric|llm_duration,metric|prompt_tokens,metric|completion_tokens,metric|total_tokens,metadata|[%22llmOptions%22%252C%22max_tokens%22],metadata|[%22maxConcurrency%22]&v=Badge+Only)
- [Uni badge questions](https://docs.google.com/spreadsheets/d/1WrBdl-KJXgphLZlTu7cohOsl1361h64sOD-sU9Hat0Q/edit?gid=1342745844#gid=1342745844) (not particularly sensitive, but please do not share externally)
=> (EAI-861): Benchmark badge questions

packages/scripts/package.json, packages/scripts/src/meta2rst.test.ts, packages/scripts/src/meta2rst.ts, packages/scripts/src/upsertMetaDirective.ts, packages/scripts/testData/meta2rst/no-meta-no-description.rst, packages/scripts/testData/meta2rst/yes-meta-no-description.rst, packages/scripts/testData/meta2rst/yes-meta-yes-description.rst
Jira: (EAI-857) Create rST meta description import tool
- Adds two new files (plus tests) to the `scripts` package
- `meta2rst` contains the implementations that process and update reStructuredText files. The test file is fairly comprehensive and probably easier to review than the arcane implementations.
- `upsertMetaDirective` which wraps the `meta2rst` functions in a script that we can call from the command line. We make this available via a new package.json script, `npm run upsertMetaDirective -- <path-to-rst-file> <meta-description>`. I tested this manually against some files in `docs-realm` and it seems to work perfectly. I'll probably wrap it up in a `.sh` file for the actual imports so that we can call it multiple time programmatically.
=> (EAI-857) Create rST meta description import tool

packages/chatbot-server-mongodb-public/src/eval/bin/generateEvalCasesYamlFromCSV.ts, packages/mongodb-rag-core/src/contentStore/MongoDbPageStore.ts, packages/mongodb-rag-core/src/eval/getConversationEvalCasesFromCSV.ts
Jira: https://jira.mongodb.org/browse/EAI-901
- log out urls listed in input CSV as references that do not exist on the pages collection
- script output with warnings about missing resources
```
npm run generate-eval-cases /Users/alla.yakubova/Downloads/DotcomChatbotEvalQs.csv dotcom_chatbot_evaluation_questions_test
> chatbot-server-mongodb-public@0.15.2 generate-eval-cases
> ts-node src/eval/bin/generateEvalCasesYamlFromCSV.ts /Users/alla.yakubova/Downloads/DotcomChatbotEvalQs.csv dotcom_chatbot_evaluation_questions_test
Reading from: /Users/alla.yakubova/Downloads/DotcomChatbotEvalQs.csv
(node:64547) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created) …
```
=> (EAI-901) check that reference urls are ingested

packages/chatbot-server-mongodb-public/src/eval/fuzzyLinkMatch.test.ts, packages/chatbot-server-mongodb-public/src/eval/fuzzyLinkMatch.ts
Jira: https://jira.mongodb.org/browse/EAI-911
- fix fuzzy match for case where one of the urls has no path. This was causing more matches than possible, leading to a score > 1, when the score must be between 0 and 1
- fixed an existing test case
- added an additional test case
- tested this with some evals, not seeing BinaryNdcgAt5 errors anymore
=> (EAI-911) fix bug causeing BinaryNdcgAt5 errors

packages/mongodb-artifact-generator/src/vectorSearch.ts, packages/mongodb-chatbot-server/src/processors/makeRagGenerateUserPrompt.test.ts, packages/mongodb-chatbot-server/src/processors/makeRagGenerateUserPrompt.ts, packages/mongodb-rag-core/src/conversations/ConversationsService.ts, packages/mongodb-rag-core/src/embed/Embedder.ts, packages/mongodb-rag-core/src/embed/OpenAiEmbedder.test.ts, packages/mongodb-rag-core/src/embed/OpenAiEmbedder.ts, packages/mongodb-rag-core/src/findContent/DefaultFindContent.test.ts, packages/mongodb-rag-core/src/findContent/DefaultFindContent.ts, packages/mongodb-rag-core/src/findContent/FindContentFunc.ts, packages/scripts/src/ScrubbedMessage.ts, packages/scripts/src/scrubMessages.test.ts, packages/scripts/src/scrubMessages.ts
Jira: (EAI-904) Store the embedding model alongside the vector
- The core `Embedder` now optionally exposes the model/deployment it uses as the `modelName` field
- The `OpenAiEmbedder` implementation does this by default
- Server stores the `embeddingModel` in each user message
- Scrubbed messages also include the `embeddingModel` field
=> (EAI-904) Store the embedding model alongside the vector

docs/docs/ui.md, packages/mongodb-chatbot-ui/src/App.tsx, packages/mongodb-chatbot-ui/src/Chatbot.tsx, packages/mongodb-chatbot-ui/src/services/conversations.test.ts, packages/mongodb-chatbot-ui/src/services/conversations.ts, packages/mongodb-chatbot-ui/src/useConversation.tsx
Jira: (EAI-926) UI supports clientContext
- Adds a `getClientContext` prop to `Chatbot` that allows clients to send arbitrary data to the server
- Updates the conversations service to accept & pass `clientContext`
=> (EAI-926) UI supports clientContext

package-lock.json, packages/scripts/package.json, packages/scripts/src/main/materializeScrubbedMessagesStats.ts, packages/scripts/src/materialize/materializedViewUtils.test.ts, packages/scripts/src/materialize/materializedViewUtils.ts, packages/scripts/src/materialize/scrubbed_messages_stats.ts
This updates the code for our materialized view stats collection that we can use to get historical operational data (e.g. num messages, num conversations) and make charts without needing to re-calculate every time. Instead we _pre-_calculate nightly.
=> Update stats materialized view script

packages/ingest-mongodb-public/src/meta.config.ts, packages/ingest-mongodb-public/src/sources/snooty/SnootyDataSource.test.ts, packages/ingest-mongodb-public/src/sources/snooty/SnootyDataSource.ts, packages/ingest-mongodb-public/src/sources/snooty/SnootyProjectsInfo.test.ts, packages/ingest-mongodb-public/src/sources/snooty/SnootyProjectsInfo.ts, packages/ingest-mongodb-public/src/sources/snootySources.ts, packages/mongodb-rag-core/src/contentStore/Page.ts
Jira: https://jira.mongodb.org/browse/EAI-968
- removed `snooty` prefix from sourceName
- ingesting all active branches for each data source
- inactive branches not ingested
- if pages exist for a branch that has recently become inactive, it will be deleted when ingest runs
- functionality to override what is considered the current version
- removed the override for docs v7.0 as [discussed in slack](https://mongodb.slack.com/archives/C05CE6UBGG5/p1745450845744029)
- updated tests
- version is saved on Page on the metadata object. This is a deviation from the [spec doc](https://docs.google.com/document/d/1abwdBxOTxKLEynxSFeFFrrY-XGu4_UIL4XWq4fsVTnA/edit?usp=sharing), where we planned to set version on the root level of the document. I made this choice bc this is where version was …
=> (EAI-968) ingest multiple versions

package-lock.json, packages/mongodb-chatbot-ui/package.json, packages/mongodb-chatbot-ui/src/App.tsx, packages/mongodb-chatbot-ui/src/segment.ts, packages/mongodb-chatbot-ui/src/services/conversations.test.ts, packages/mongodb-chatbot-ui/src/services/conversations.ts, packages/mongodb-chatbot-ui/src/useConversation.test.tsx, packages/mongodb-chatbot-ui/src/useConversation.tsx
Jira: (EAI-997) [UI] Segment fixes
- Strips literal quotes from segment ids (if present)
- Supports dynamic fetchOptions in conversations service
- This lets us pull the segment headers on every request. Useful if they're not set until after the chatbot renders.
=> Segment fixes

packages/chatbot-server-mongodb-public/src/tracing/extractTracingData.ts, packages/chatbot-server-mongodb-public/src/tracing/getLlmAsAJudgeScores.test.ts, packages/chatbot-server-mongodb-public/src/tracing/routesUpdateTraceHandlers.ts, packages/mongodb-chatbot-server/src/routes/conversations/commentMessage.ts
Jira: https://jira.mongodb.org/browse/EAI-998
- Add new metrics to conversation tracing
- Track if message is rated (0 if not, 1 if so)
- Track if message is commented (0 if not, 1 if so)
- Update existing metrics to compute across all traces
- Redo `RejectedQuery` as InputGuardrailPass`. 1 if passes guardrail, 0 if not.
- Redo `LlmDoesNotKnow` as `LlmAnswerAttempted`. 1 if attempts answer (not the canned idk response), 0 if canned answer
- `VerifiedAnswer` now calculates 1 if verified answer, 0 if not. Previously was only calculated if it was a verified answer. 
- This gives us better top-line numbers to view in braintrust logs, as the metrics are now across all messages, rather than just the ones where there was a pass.
=> (EAI-998): Low-hanging improvements to existing tracing metrics

packages/ingest-mongodb-public/src/sources/mongoose.ts, packages/ingest-mongodb-public/src/sources/snooty/SnootyProjectsInfo.test.ts, packages/mongodb-artifact-generator/src/test/MockPageStore.ts, packages/mongodb-rag-core/src/contentStore/MongoDbPageStore.test.ts, packages/mongodb-rag-core/src/contentStore/MongoDbPageStore.ts, packages/mongodb-rag-core/src/contentStore/Page.ts, packages/mongodb-rag-core/src/dataSources/handleHtmlDocument.test.ts, packages/mongodb-rag-core/src/test/MockPageStore.ts
Jira: https://jira.mongodb.org/browse/EAI-1003
- getDataSourceVersions returns a list of available versions for a given data source
- tests
-
=> (EAI-1003) get available versions for data source

packages/ingest-mongodb-public/src/sources/DevCenterDataSource.test.ts, packages/ingest-mongodb-public/src/sources/DevCenterDataSource.ts, packages/ingest-mongodb-public/src/sources/snooty/SnootyDataSource.ts, packages/mongodb-rag-core/src/contentStore/EmbeddedContent.ts, packages/mongodb-rag-core/src/contentStore/MongoDbEmbeddedContentStore.test.ts, packages/mongodb-rag-core/src/contentStore/MongoDbEmbeddedContentStore.ts, packages/mongodb-rag-core/src/contentStore/Page.ts, packages/mongodb-rag-core/src/contentStore/updateEmbeddedContent.ts
Jira: https://jira.mongodb.org/browse/EAI-1001
- "metadata.pageType" field added
- SnootyDataSource creates pages with `"metadata.pageType": "tech-docs"`
- DevCenterDataSource creates pages with `"metadata.pageType": "devcenter"`
- index created for new field, vector search index updated to include new field
- This will allow us to change the filter [here](https://github.com/mongodb/chatbot/blob/EAI-428-feature-versioned-docs/packages/datasets/src/mongoDbDatasetConstants.ts#L19-L22) to find public datasets (snooty or devcenter) by filtering on the "metadata.pageType" field
=> (EAI-1001) enable search by type

packages/benchmarks/src/nlPromptResponse/NlQuestionAnswerEval.ts, packages/benchmarks/src/nlPromptResponse/bin/techSupport/techSupportPromptCompletionBenchmark.ts, packages/benchmarks/src/reporting/EvalCases.ts, packages/benchmarks/src/reporting/bin/reportMultipleChoiceBenchmarkResults.ts, packages/benchmarks/src/reporting/bin/reportTechSupportBenchmarkResults.ts, packages/benchmarks/src/reporting/getBraintrustExperimentSummary.ts, packages/benchmarks/src/reporting/listBraintrustExperiments.ts, packages/benchmarks/src/reporting/materializeExperimentResultsByCase.test.ts, packages/benchmarks/src/reporting/materializeExperimentResultsByCase.ts, packages/benchmarks/src/reporting/reportBenchmarkResults.ts
Jira: https://jira.mongodb.org/browse/EAI-1015
- Parse Braintrust results to benchmark reporting service format
- Implement for "prompt_response" style benchmarks
- Generate results for the tech support benchmark. shared in slack.
=> (EAI-1015): Parse Braintrust results to benchmark reporting service format

packages/mongodb-rag-core/src/mongoDbMetadata/classifyMetadata.eval.ts, packages/mongodb-rag-core/src/mongoDbMetadata/classifyMetadata.ts, packages/mongodb-rag-core/src/mongoDbMetadata/products.ts, packages/mongodb-rag-core/src/mongoDbMetadata/topics.ts
Jira: https://jira.mongodb.org/browse/EAI-977
Braintrust project: https://www.braintrust.dev/app/mongodb-education-ai/p/classify-mongodb-metadata 
- Copies eval cases from `packages/chatbot-server-mongodb-public/src/processors/extractMongoDbMetadataFromUserMessage.eval.ts` to `packages/mongodb-rag-core/src/mongoDbMetadata/classifyMetadata.eval.ts`
- also add topic correct evaluator fxn
- Add topic name/description to topic classification system prompt 
- add more eval cases
=> (EAI-977) Add Braintrust evals to core metadata classifiers

packages/chatbot-server-mongodb-public/evalCases/conversations.yml, packages/chatbot-server-mongodb-public/src/config.ts, packages/chatbot-server-mongodb-public/src/processors/generateResponseWithSearchTool.test.ts, packages/chatbot-server-mongodb-public/src/processors/generateResponseWithSearchTool.ts, packages/chatbot-server-mongodb-public/src/systemPrompt.ts, packages/chatbot-server-mongodb-public/src/tools/search.eval.ts, packages/chatbot-server-mongodb-public/src/tools/search.ts, packages/chatbot-server-mongodb-public/src/tracing/extractTracingData.test.ts, packages/chatbot-server-mongodb-public/src/tracing/extractTracingData.ts, packages/chatbot-server-mongodb-public/src/tracing/getLlmAsAJudgeScores.test.ts, packages/mongodb-chatbot-server/src/processors/MakeReferenceLinksFunc.ts, packages/mongodb-chatbot-server/src/processors/SearchResult.ts, packages/mongodb-chatbot-server/src/processors/index.ts
Jira: https://jira.mongodb.org/browse/EAI-1050
Misc clean up to retrieval as a tool
- move `generateResponseWithSearch` to `chatbot-server-mongodb-public`
- Clean up tool return type to avoid 2x JSON stringification
- add metadata to user message, following pattern of previous RAG system
- Must be merged after https://github.com/mongodb/chatbot/pull/757
=> (EAI-1050): Retrieval as a tool clean up

package.json, packages/scripts/environments/production.yml, packages/scripts/environments/staging.yml, packages/scripts/package.json
Jira: https://jira.mongodb.org/browse/EAI-1053
- Fixes the following error by making all npm commands reference the correct filename (singular, verifyPagesInSource, not plural)
` npm error Missing script: "scripts:verifyPagesInSources" `
=> (EAI-1053) Fix to page validation script runner command

packages/ingest-mongodb-public/src/sources/mongodb-university/MongoDbUniversityDataApiClient.ts
Jira: https://jira.mongodb.org/browse/EAI-1157
- reduce limit from 300 to 250 to avoid lambda limits
-
- This change was made on the suggestion of the UP team, who explained they have a cap they are unable to raise for the lambda invocation payload https://jira.mongodb.org/browse/UP-7665
=> (EAI-1157) fix breaking university data source tests

packages/chatbot-server-mongodb-public/src/config.ts, packages/chatbot-server-mongodb-public/src/processors/generateResponseWithSearchTool.test.ts, packages/chatbot-server-mongodb-public/src/processors/generateResponseWithSearchTool.ts, packages/mongodb-chatbot-server/src/processors/makeVerifiedAnswerGenerateResponse.test.ts, packages/mongodb-chatbot-server/src/processors/makeVerifiedAnswerGenerateResponse.ts, packages/mongodb-chatbot-server/src/routes/responses/createResponse.test.ts, packages/mongodb-chatbot-server/src/routes/responses/createResponse.ts, packages/mongodb-chatbot-server/src/routes/responses/errors.ts, packages/mongodb-chatbot-server/src/routes/responses/responsesRouter.test.ts, packages/mongodb-chatbot-server/src/test/testConfig.ts, packages/mongodb-chatbot-server/src/test/testHelpers.ts, packages/mongodb-rag-core/package.json, packages/mongodb-rag-core/src/DataStreamer.test.ts, packages/mongodb-rag-core/src/DataStreamer.ts, packages/mongodb-rag-core/src/openai.ts
Jira: https://jira.mongodb.org/browse/EAI-1154
- implement data streaming for responses api
- matches openai spec for response data and errors
-
=> handle data streaming for new responses API

packages/chatbot-server-mongodb-public/src/eval/fuzzyLinkMatch.ts, packages/chatbot-server-mongodb-public/src/tools/fetchPage.ts, packages/ingest-mongodb-public/src/sources/DevCenterDataSource.ts, packages/ingest-mongodb-public/src/sources/index.ts, packages/ingest-mongodb-public/src/sources/mongodb-university/makeUniversityPages.ts, packages/ingest-mongodb-public/src/sources/mongodbDotCom/WebDataSource.test.ts, packages/ingest-mongodb-public/src/sources/mongodbDotCom/WebDataSource.ts, packages/ingest-mongodb-public/src/sources/mongodbDotCom/webSources.ts, packages/ingest-mongodb-public/src/sources/mongoose.ts, packages/ingest-mongodb-public/src/sources/practicalAggregations.ts, packages/ingest-mongodb-public/src/sources/prisma.ts, packages/ingest-mongodb-public/src/sources/snooty/SnootyDataSource.test.ts, packages/ingest-mongodb-public/src/sources/snooty/SnootyDataSource.ts, packages/ingest-mongodb-public/src/sources/wiredTiger.ts, packages/mongodb-rag-core/src/dataSources/normalizeUrl.test.ts, packages/mongodb-rag-core/src/dataSources/normalizeUrl.ts, packages/scripts/src/checkUrlsAgainstDB.ts
Jira: https://jira.mongodb.org/browse/EAI-1168
- Option to remove query string & hash fragment in normalizeUrl
- I made these configurable because there could be future cases where we don't want to remove them (e.g. before, in ingest, we had 4 unique pages for the same URL, only difference was the URL hash fragments)
=> EAI-1168 Remove query string, hash fragment in normalizeUrl

docs/docs/server/openapi.yaml
Jira: https://jira.mongodb.org/browse/EAI-971
- Adds route and components of new search route to openapi documentation spec
=> (EAI-971) Add `searchContent` to openapi spec documentation

docs/docs/server/openapi.yaml
Jira: https://jira.mongodb.org/browse/EAI-1184
- Document MongoDB Knowledge Service Responses API
To view the rendered spec:
1. Clone repo (`git clone https://github.com/mongodb/chatbot.git`)
a. If viewing on this branch, open the branch EAI-1184
3. `cd docs && npm i && npm start`. This should start the dev server of the docs site
4. In browser, open link http://localhost:3000/chatbot/server/openapi#tag/Responses/operation/createResponse. You should see the spec rendered in an OpenAPI viewer.
=> (EAI-1184): Document Responses API

packages/chatbot-server-mongodb-public/src/processors/mongoDbInputGuardrail.eval.ts, packages/chatbot-server-mongodb-public/src/processors/mongoDbInputGuardrail.ts
Jira: https://jira.mongodb.org/browse/EAI-1180
- Add VoyageAI company and its embedding models as allowed query topics to guardrail
- [guardrail eval](https://www.braintrust.dev/app/mongodb-education-ai/p/user-message-guardrail/experiments/gpt-4.1-nano-970ed90d?c=gpt-4.1-nano-43f2de8f&tg=false)
- [conversations eval (voyage cases)](https://www.braintrust.dev/app/mongodb-education-ai/p/mongodb-chatbot-conversations/experiments/mongodb-chatbot-voyage-in-guardrail?c=mongodb-chatbot-skills-questions-fcd08da7&tg=false)
=> (EAI-1180) VoyageAI allowed in guardrail

docs/docs/server/openapi.yaml, packages/chatbot-server-mongodb-public/src/config.ts, packages/mongodb-chatbot-server/src/routes/content/contentRouter.test.ts, packages/mongodb-chatbot-server/src/routes/content/contentRouter.ts, packages/mongodb-chatbot-server/src/routes/content/listDataSources.test.ts, packages/mongodb-chatbot-server/src/routes/content/listDataSources.ts, packages/mongodb-chatbot-server/src/routes/content/searchContent.ts, packages/mongodb-rag-core/src/contentStore/EmbeddedContent.ts, packages/mongodb-rag-core/src/contentStore/MongoDbEmbeddedContentStore.test.ts, packages/mongodb-rag-core/src/contentStore/MongoDbEmbeddedContentStore.ts, packages/mongodb-rag-core/src/contentStore/updateEmbeddedContent.test.ts, packages/mongodb-rag-core/src/findContent/BoostOnAtlasSearchFilter.test.ts
Jira: https://jira.mongodb.org/browse/EAI-1173
- Adds new GET `/content/sources` endpoint to list all data sources possible
- Adds route handler and tests for route handler
- Adds documentation for new route in openapi yaml
=> (EAI-1173) Content sources endpoint

packages/chatbot-server-mongodb-public/src/responsesApi.test.ts, packages/mongodb-chatbot-server/src/routes/conversations/addMessageToConversation.ts, packages/mongodb-chatbot-server/src/routes/responses/createResponse.ts, packages/mongodb-chatbot-server/src/utils.ts, packages/mongodb-rag-core/src/aiSdk.ts, packages/mongodb-rag-core/src/braintrust.ts
Jira: https://jira.mongodb.org/browse/EAI-1201
- Add Braintrust tracing to Responses API. 
- Tracing in Responses API is conditional on `store !== false`. If `store: false`, provide a tombstone trace in Braintrust that contains no data besides the IDs.
- Included tests to see that this works, but skipped b/c there is currently no way to validate functionality besides through the Braintrust UI, to best of my knowledge.
- Examples of this working:
- [Tombstone](https://www.braintrust.dev/app/mongodb-education-ai/p/chatbot-responses-dev/logs?range=%223d%22&r=688a432697349958d96b0486)
- [Populated information](https://www.braintrust.dev/app/mongodb-education-ai/p/chatbot-responses-dev/logs?range=%223d%22&r=688a432297349958d96b047f)
=> (EAI-1201): Add Braintrust tracing to Responses API

docs/docs/server/openapi.yaml, packages/mongodb-chatbot-server/src/processors/makeVerifiedAnswerGenerateResponse.test.ts, packages/mongodb-chatbot-server/src/processors/makeVerifiedAnswerGenerateResponse.ts, packages/mongodb-rag-core/src/DataStreamer.ts
Jira: https://jira.mongodb.org/browse/EAI-1189
- Stream Responses API Verified Answer metadata
- Document changes
- Also small fix to existing url_citation annotation spec
- We have to do a bit of a hacky implementation here b/c there's no clean, spec compliant way to stream the verified answer metdata. This PR contains my best attempt to include the verified answer metadata in way that balances spec compliance with being relatively reasonable.
=> (EAI-1189): Stream Responses API verified answer metadata

docs/docs/server/openapi.yaml, packages/chatbot-server-mongodb-public/src/config.ts
Jira: n/a
- Support 50 user messages in Responses API convo
- update docs accordingly
- IDK why it was only 6 before 🤔
=> Support 50 user messages in Responses API convo

packages/scripts/environments/production.yml, packages/scripts/environments/staging.yml, packages/scripts/src/profound/getAndProcessAnswers.ts
Jira: https://jira.mongodb.org/browse/EAI-1245
- replaced UTC dates with local dates to match what Profound expects
- update cron schedule to run after profound is done running prompts for the day 
Notes on Profound and handling timezone, quotes are taken from [this slack conversation](https://mongodb.slack.com/archives/C07U8029681/p1754423135991149).
- According to Profound, 
> API responses are returned as UTC timestamps, but the input is parsed as EST.
So, an input of 2025-08-04 is parsed as EST and becomes 2025-08-04 04:00:00 UTC. The timestamps in the returned responses are UTC timestamps.
This is because our system executes prompts within a 12-hour EST time window, which is 4 a.m. UTC
- Profound support suggested querying by YYYY-MM-DD without any timestamps or timezone indication. …
=> (EAI-1245) querying Profound API with local (EDT) dates

packages/mongodb-chatbot-server/src/routes/responses/createResponse.test.ts, packages/mongodb-chatbot-server/src/routes/responses/createResponse.ts
Jira: https://jira.mongodb.org/browse/EAI-1202
- Fixes generation missing context for multiple input messages. (When request `input` was a list & `previous_response_id` was not given, `loadConversationByMessageId` would get an empty conversation and use that for generation instead of the input messages.)
=> (EAI-1202): [bug_fix] Missing context for multiple input messages on Responses API

packages/chatbot-server-mongodb-public/src/processors/generateResponseWithTools.test.ts, packages/chatbot-server-mongodb-public/src/processors/generateResponseWithTools.ts
Jira: https://jira.mongodb.org/browse/EAI-1268
- Fixes cases where LLM generation loop finishes before guardrail does by waiting for guardrail to resolve before streaming results
- And unit test it
- without this, for short messages that trip the guardrail, 2 results are streamed to chatbot UI/responses API, one for LLM response and one for guardrail rejection
- [Braintrust](https://www.braintrust.dev/app/mongodb-education-ai/p/mongodb-chatbot-conversations/experiments/EAI-1268-race-condition-again) run looks good, no dropoffs
=> (EAI-1268) Fix guardrail race condition (x2!)

docs/docs/server/context-engineering.md, docs/docs/server/evaluation.md, docs/sidebars.ts
Jira: https://jira.mongodb.org/browse/EAI-1272
- Add docs page for context engineering. based on experience w/ the current chatbots in development
- Added placeholder for the soon-to-be-created Evaluation guide since the context engineering guide links to it
-
=> (EAI-1272): [docs] Context engineering guide
