design_docs/openapi.yml

Use a resource-oriented approach (e.g. `POST /conversations`, or `GET /conversations/64876105b8480835ec6d6df4`)

Update Q&A Server OpenAPI Spec

---

chat-server/.env.example
chat-server/package-lock.json
chat-server/package.json
chat-server/src/integrations/openai.ts
chat-server/src/routes/conversations.ts
chat-server/src/services/database.ts
chat-server/src/services/llm.ts
chat-server/tests/integrations/openai.test.ts
chat-server/tests/services/llm.test.ts
chat-server/types.d.ts

Add OpenAI LLM service. includes prompts. 
includes unit tests on I/0 functionality, but not LLM/prompt quality. LLM qualitative tests will come later.
~Must be merged after https://github.com/mongodb/docs-chatbot/pull/6 b/c it's based off of changes in that branch. Rebase on top of `main` once #6 has been merged.~

(DOCSP-30617): OpenAI LLM service

---

chat-server/src/routes/conversations/rateMessage.ts
chat-server/src/services/conversations.ts
chat-server/tests/routes/conversations.test.ts
chat-ui/src/Chatbot.tsx
chat-ui/src/services/conversations.ts
chat-ui/src/useConversation.tsx

backend endpoint + ui handling of endpoint

(DOCSP-30577): POST `/conversations/:conversationId/messages/:messageId/rating` endpoint

---

chat-server/src/app.ts
chat-server/src/routes/conversations/addMessageToConversation.ts
chat-server/src/routes/conversations/createConversation.ts
chat-server/src/routes/conversations/rateMessage.ts
chat-server/src/utils.ts

Jira: https://jira.mongodb.org/browse/DOCSP-31231
- track reqId in logs
- standardize logging on requests to server

(DOCSP-31121): Add request tracking across logs

---

chat-ui/src/App.module.css
chat-ui/src/App.tsx
chat-ui/src/Chatbot.module.css
chat-ui/src/Chatbot.tsx
chat-ui/src/Message.module.css
chat-ui/src/MessageList.module.css

Jira: (DOCSP-30890) [UI] Make component mobile responsive
- Responsive styles for Small, Medium, and Large+ screens ([as defined in Snooty](https://github.com/mongodb/snooty/blob/master/src/theme/docsTheme.js#L39-L47))
- Adds a modal close button

(DOCSP-30890) [UI] Make component mobile responsive

---

chat-server/src/aiConstants.ts
chat-ui/index.html

Jira: n/a
- Make prompt and temperature stricter to reduce risk of hallucinated code examples
- Change demo page title from boilerplate

stricter LLM to reduce halucination risk + change demo page title

---

ingest/src/DevCenterDataSource.test.ts

Jira: N/A
- Fixes test given so many discarded results
- Checks URL sanity

Fix + improve devcenter source tests

---

chat-ui/src/App.tsx
chat-ui/src/Chatbot.tsx

Jira:
- See (DOCSP-31201) [UI] Updated Legalese
- Updates the legal text beneath the inactive input (i.e. the default state)
- Adds the "Verify Information" banner to all active states

(DOCSP-31201) [UI] Updated Legalese

---

chat-ui/README.md
chat-ui/src/Chatbot.tsx
chat-ui/src/utils.ts

Jira: (DOCSP-33291) [UI] Add tck tracking to links
- Add `tck` prop + default for link analytics

(DOCSP-33291) [UI] Add tck tracking to links

---

chat-ui/.release-it.json
chat-ui/__mocks__/@microsoft/fetch-event-source.ts
chat-ui/package.json
chat-ui/src/services/conversations.test.ts
chat-ui/src/services/conversations.ts
chat-ui/vitest.config.ts
package-lock.json

Jira: (DOCSP-31104) [UI] Add tests to FE services
- Adds tests for chat-ui services
- No tests yet for the UI code itself (e.g. via react-testing-library) due to some unresolved ESM integration issues

(DOCSP-31104) [UI] Add tests to FE services

---

chat-server/src/routes/conversations/addMessageToConversation.test.ts
chat-server/src/routes/conversations/rateMessage.test.ts
chat-server/src/routes/conversations/rateMessage.ts
chat-server/src/routes/conversations/utils.ts
chat-server/src/services/conversations.test.ts
chat-server/src/services/conversations.ts
scripts/src/ScrubbedMessage.ts
scripts/src/analyzeMessages.ts
scripts/src/scrubMessages.ts

Jira: none
- Refactors Messages to use a more TypeScript-y pattern (even though it is somewhat more annoying to use)

Add whether message was deemed "Do not answer" to conversation

---

scripts/package.json
scripts/src/createView/scrubbed_messages_by_rating.ts
scripts/src/createView/scrubbed_top_250_references.ts
scripts/src/createView/scrubbed_topics.ts

Jira: (DOCSP-33445) [ANALYTICS] Scrubbed Views
- Adds views with similar shape to those in https://github.com/mongodb/chatbot/pull/192 for scrubbed messages

(DOCSP-33445) [ANALYTICS] Scrubbed Views

---

chat-core/src/ApiEmbeddedContent.ts
chat-core/src/ApiPage.ts
chat-core/src/index.ts
chat-server/src/services/ChatLlm.ts
chat-server/src/services/OpenAiApiChatLlm.ts

Jira: https://jira.mongodb.org/browse/DOCSP-
- taken from https://github.com/mongodb/chatbot/pull/209/ and put in appropriate places in the repo
-
-

Add some core logic + types for us to build on 

---

chat-ui/src/Message.tsx

Jira: (DOCSP-33938) [UI] Fix nested newline spacing

(DOCSP-33938) [UI] Fix nested newline spacing

---

chat-ui/package.json
chat-ui/src/index.tsx
chat-ui/src/services/conversations.test.ts
chat-ui/src/services/conversations.ts
chat-ui/src/useConversation.tsx
package-lock.json

Jira: (EAI-123) [UI] Replace chat-core with mongodb-rag-core

(EAI-123) [UI] Replace chat-core with mongodb-rag-core

---

README.md

Jira: https://jira.mongodb.org/browse/EAI-141
- Add link to dev center blog post in README
-

(EAI-141): Add link to dev center blog post in README

---

chat-ui/package.json
package-lock.json

Jira: (EAI-7) [UI] Can't send existing text after reopening modal
1. Ask a question
2. Wait for the response
3. Enter some text for a follow up question but don't send it (you can do this while the response is streaming or wait til after)
4. Close the modal
5. Re-open the modal
6. At this point the InputBar correctly renders the text you entered in 3 ~but the send button is disabled~ **and the send button is enabled**.

(EAI-7) [UI] Can't send existing text after reopening modal

---

chat-ui/src/services/conversations.test.ts
chat-ui/src/services/conversations.ts

Jira: (EAI-150) [UI] change "Further Reading" in chatbot response to "Related Resources"
- Slight wording change

(EAI-150) [UI] change "Further Reading" in chatbot response to "Related Resources"

---

chat-ui/package.json
package-lock.json

Jira: (EAI-145) [UI] InputBar does not add newlines on shift+enter
- Now you can press {shift|ctrl}+enter to expand the input bar height (up to 5 lines)

(EAI-145) InputBar adds newlines on shift+enter

---

ingest-mongodb-public/package.json
ingest-mongodb-public/src/sources.ts
ingest-mongodb-public/src/sources/wiredTiger.ts

Jira: https://jira.mongodb.org/browse/EAI-36
- Add WiredTiger data source
- note that added file to new `/sources` directory here. this is so that the new file falls into the directory added in https://github.com/mongodb/chatbot/pull/250

(EAI-36): WiredTiger data source

---

.drone.yml
chat-server/package.json
chat-server/src/app.test.ts
chat-server/src/app.ts
chat-server/src/index.ts
chat-server/src/routes/index.ts
chat-server/src/routes/staticSite.test.ts
chat-server/src/routes/staticSite.ts
chat-ui/vite.config.static-site.ts
chatbot-server-mongodb-public/package.json
chatbot-server-mongodb-public/src/config.ts
examples/basic-chatbot-server/package-lock.json
examples/basic-chatbot-server/package.json
examples/basic-chatbot-server/src/index.ts
examples/basic-chatbot-server/tsconfig.json
package-lock.json
package.json

Jira: https://jira.mongodb.org/browse/EAI-49
- Add static site endpoint to `mongodb-chatbot-server`
- Include static site usage in implementations
- note: not including in prod site..handled by runtime config
- already deployed to staging to validate functionality

(EAI-49): Add static site endpoint to `mongodb-chatbot-server` + include in implementations

---

package-lock.json
packages/ingest-mongodb-public/package.json
packages/mongodb-rag-ingest/package.json

Jira: n/a
- prod release of ingest with new data sources
-

ingest-mongodb-public@0.1.7 release

---

package-lock.json
packages/ingest-mongodb-public/.release-it.json
packages/ingest-mongodb-public/package.json

Ingest v0.1.0

---

.drone.yml

Jira: n/a
- fix git tag name for prod ingest deploy
-
-

fix prod ingest deploy

---

ingest-service.dockerfile

Jira: n/a
- fix ingest cron working dir to include `/packages/` in path
-
-

fix docker working dir

---

.drone.yml
package-lock.json
package.json
packages/scripts/environments/production.yml
packages/scripts/environments/staging.yml
packages/scripts/package.json
scripts-service.dockerfile

Jira: n/a
- Fix scripts cron by running scripts from monorepo package.json
-
-

Scripts k8s fix

---

package-lock.json
packages/ingest-mongodb-public/.release-it.json
packages/ingest-mongodb-public/package.json

Jira: n/a
- update release scripts
- new ingest release
-

Ingest prod deploy

---

packages/mongodb-rag-ingest/src/sources/snooty/snootyAstToMd.test.ts
packages/mongodb-rag-ingest/src/sources/snooty/snootyAstToMd.ts
packages/mongodb-rag-ingest/testData/sampleCompoundTitlePageAst.json

Jira: https://jira.mongodb.org/browse/EAI-147
- Grabs all text nodes from headings, rather than first

(EAI-147): Fix title parsing when text spans multiple nodes

---

packages/mongodb-rag-core/src/MongoDbPageStore.test.ts
packages/mongodb-rag-core/src/MongoDbPageStore.ts
packages/mongodb-rag-core/src/Page.ts

Jira: (EAI-174) [Core] Support arbitrary MongoDB queries in PageStore

(EAI-174) [Core] Support arbitrary MongoDB queries in PageStore

---

package-lock.json
packages/chatbot-server-mongodb-public/.release-it.json
packages/ingest-mongodb-public/.release-it.json
packages/mongodb-chatbot-server/.release-it.json
packages/mongodb-chatbot-server/package.json
packages/mongodb-chatbot-ui/.release-it.json
packages/mongodb-rag-core/.release-it.json
packages/mongodb-rag-core/package.json
packages/mongodb-rag-ingest/.release-it.json
packages/scripts/.release-it.json

Jira: n/a
- Update release-it config to work better and be cleaner
- new releases for `mongodb-rag-core` and `mongodb-chatbot-server`
-

Cutting releases updates + 2 new releases

---

docs/docs/server/conversations.md
docs/docusaurus.config.ts

Jira: n/a
- have to remove throw on broken links b/c the generated reference docs produce some bad links 😢 
-
- [sorry nick](https://github.com/mongodb/chatbot/pull/268#discussion_r1430513618)

allow broken links b/c some generated reference docs broken links

---

docs/docs/ui.md
packages/mongodb-chatbot-ui/README.md

Jira: n/a
- Restructure chatbot UI docs for clarity + better header sidebar rendering for docusaurus
-

UI Docs Update

---

docs/docs/ui.md
packages/mongodb-chatbot-ui/README.md
packages/mongodb-chatbot-ui/src/Chatbot.tsx

Jira: (EAI-184) [UI] Chatbot provider should allow multiple children
- `Chatbot` now allows either one or multiple children (but not zero)

(EAI-184) [UI] Chatbot provider should allow multiple children

---

packages/mongodb-chatbot-server/README.md
packages/mongodb-chatbot-server/package.json
packages/mongodb-chatbot-ui/README.md
packages/mongodb-chatbot-ui/package.json
packages/mongodb-rag-core/package.json
packages/mongodb-rag-ingest/README.md
packages/mongodb-rag-ingest/package.json

Jira: https://jira.mongodb.org/browse/EAI-183
- Update public package README to refer to the MongoDB Chatbot Framework and its docs
- Update public packages' package.json files w/ relevant docs and tags
- Upon approval, will publish all packages to have these changes live on npm.

(EAI-183): Update READMEs and package.json files

---

docs/docs/index.md
docs/docusaurus.config.ts
docs/src/css/custom.css

Jira: n/a
- Add GH logo to main nav
- Add link to home on footer
- Clean up config file comments
- Update metadata description of homepage
-

docs config  +metadata updates

---

docs/docs/server/evaluate.md

Jira: n/a
- bundled ui doesn't work. let's not talk about it in the docs
- also less necessary now b/c can easily get UI from quick start.
-

docs: remove mention of bundled UI

---

docs/docs/ingest/configuration-reference.md
docs/docs/ingest/configure.md
docs/docs/ingest/data-sources.md

Jira: n/a
- Correct ~fine tune~ to optimize to fit new page name
- Fix broken link
-

docs copy edits

---

package.json
packages/scripts/environments/production.yml
packages/scripts/environments/staging.yml

Part of https://jira.mongodb.org/browse/EAI-177

Add findFaq cron

---

packages/scripts/environments/production.yml
packages/scripts/environments/staging.yml

- Apparently they must be lowercase

Fix cron names

---

package.json
packages/scripts/package.json
packages/scripts/src/getConversationText.ts

```
npm run scripts:getConversationText -- <Conversation._id>
```
```
npm run scripts:getConversationText -- 65aaf4dd36a5cac6e828b6be
```
```
USER: How do you import or migrate data into MongoDB Atlas?
ASSISTANT: You can import or migrate data into MongoDB Atlas using the following methods:\n\n1. Live Migration: If both the source and destination clusters are running MongoDB 6.0.8 or later, you can use the guided live migration feature in the Atlas UI. There are two types of live migration available: "pull" and "push". For detailed instructions, you can refer to the following pages in the Atlas documentation:\n   - [Live Migrate (Pull) a MongoDB 6.0.8 or Later Cluster into Atlas](https://docs.atlas.mongodb.com/import/live-migration-pull/)\n   - [Live Migrate (Push) a MongoDB 6.0.8 or …
```

Script: Get the text transcript of a conversation

---

.drone.yml

- `chat-server-v*` -> `chatbot-server-mongodb-public-v*`

Update git tag used to deploy chatbot-server-mongodb-public to prod

---

docs/docs/server/openapi.yaml

Jira: n/a
- Update the OpenAPI spec to describe streaming behavior.
- Minor cosmetic updates.
- I wasn't able to get the example for the stream response to render well. Based on googling, seems it's a bug. I think it's acceptable as is.

Update openapi spec w/ streaming behavior

---

packages/mongodb-chatbot-ui/package.json

Fixes the issue described in https://github.com/mongodb/chatbot/issues/324#issuecomment-1933287837
- Adds `@lg-chat/message-feedback` to `bundledDependencies`
NOTE: I will release a new build after this is merged (`mongodb-chatbot-ui@0.3.1`)

Bundle @lg-chat/message-feedback

---

package-lock.json
packages/chatbot-server-mongodb-public/.release-it.json
packages/chatbot-server-mongodb-public/package.json

Jira: https://jira.mongodb.org/browse/EAI-228
- release latest mongodb chatbot server to prod
- remove test from release it b/c it runs in CI/CD
-

Release mongodb chatbot server @0.2.0

---

package-lock.json
packages/mongodb-chatbot-ui/src/Message.tsx
packages/mongodb-chatbot-ui/src/ModalView.tsx
packages/mongodb-chatbot-ui/src/useChatbot.tsx

Jira: (EAI-223) [UI] Throttle suggested prompts
- Only runs the `onPromptSelected` callback when `showPrompts` is `true` + set `showPrompts` to `false` on the first click.

(EAI-223) [UI] Throttle suggested prompts

---

packages/mongodb-rag-ingest/src/sources/LangchainDocumentLoaderDataSource.test.ts

Jira: https://jira.mongodb.org/browse/EAI-231
- Fix flaky test
-

(EAI-231): Fix flaky Langchain DocumentLoader test

---

.drone.yml

- Added it everywhere since package.json changes are likely to merit rebuild for staging?
-

Update drone paths to include root package(-lock).json changes

---

package-lock.json
packages/mongodb-artifact-generator/package.json
packages/mongodb-artifact-generator/src/commands/parseDriversCsv.ts
packages/mongodb-artifact-generator/src/commands/translateCode.ts
packages/mongodb-artifact-generator/src/runlogger.ts

- Support bulk generation based on the [Drivers AI Pilot Gas Tank](https://docs.google.com/spreadsheets/d/1gQ1oHeV22cszGjl9CSl3fdH0HVJISY6NIdcEDBNW9ug/edit#gid=0) format
- Small prompt adjustments & QoL fixes for the translate commands

Drivers Artifacts

---

packages/mongodb-chatbot-eval/.env.example
packages/mongodb-chatbot-eval/package.json
packages/mongodb-chatbot-eval/src/CommandMetadataStore.test.ts
packages/mongodb-chatbot-eval/src/CommandMetadataStore.ts
packages/mongodb-chatbot-eval/src/evaluate/EvaluationStore.test.ts
packages/mongodb-chatbot-eval/src/evaluate/EvaluationStore.ts
packages/mongodb-chatbot-eval/src/generate/GeneratedDataStore.test.ts
packages/mongodb-chatbot-eval/src/generate/GeneratedDataStore.ts
packages/mongodb-chatbot-eval/src/report/ReportStore.test.ts
packages/mongodb-chatbot-eval/src/report/ReportStore.ts

Jira: https://jira.mongodb.org/browse/EAI-234

(EAI-234): Create mongodb chatbot eval data store MongoDB implementations

---

package-lock.json
packages/mongodb-chatbot-server/package.json
packages/mongodb-chatbot-ui/package.json

- release server and ui libs
-
-

2024 21 02 releases

---

packages/ingest-mongodb-public/src/sources/practicalAggregations.test.ts
packages/ingest-mongodb-public/src/sources/practicalAggregations.ts

Fix practical aggregations links

---

package-lock.json
packages/mongodb-chatbot-server/package.json

Release mongodb-chatbot-server v0.8.0

---

packages/chatbot-eval-mongodb-public/.env.example
packages/chatbot-eval-mongodb-public/package.json
packages/chatbot-eval-mongodb-public/src/eval.config.ts
packages/mongodb-chatbot-eval/src/commands/evaluate.ts
packages/mongodb-chatbot-eval/src/commands/report.ts
packages/mongodb-chatbot-eval/src/evaluate/EvaluationStore.test.ts
packages/mongodb-chatbot-eval/src/evaluate/EvaluationStore.ts
packages/mongodb-chatbot-eval/src/evaluate/checkResponseQuality.ts
packages/mongodb-chatbot-eval/src/evaluate/generateEvalsAndMetadata.test.ts
packages/mongodb-chatbot-eval/src/generate/getConversationsTestCasesFromYaml.test.ts
packages/mongodb-chatbot-eval/src/report/ReportEvalFunc.ts
packages/mongodb-chatbot-eval/src/report/ReportStore.test.ts
packages/mongodb-chatbot-eval/src/report/ReportStore.ts
packages/mongodb-chatbot-eval/src/report/generateReportAndMetadata.test.ts
packages/mongodb-chatbot-eval/src/report/generateReportAndMetadata.ts
packages/mongodb-chatbot-eval/src/report/index.ts
packages/mongodb-chatbot-eval/src/report/reportConversationStatsForEvalRun.test.ts
packages/mongodb-chatbot-eval/src/report/reportConversationStatsForEvalRun.ts
packages/mongodb-chatbot-eval/src/test/mockEvaluationStore.ts
packages/mongodb-chatbot-eval/src/test/mockReportFunc.ts
packages/mongodb-chatbot-eval/src/test/mockReportStore.ts
packages/mongodb-chatbot-server/src/routes/conversations/conversationsRouter.ts
packages/mongodb-chatbot-server/src/routes/conversations/createConversation.ts
packages/mongodb-chatbot-server/src/services/ConversationsService.ts

Jira: https://jira.mongodb.org/browse/EAI-260

(EAI-260): Report command + report on most recent `conversation_quality` func + implementation

---

docs/docs/server/rag/retrieve.md

Jira: https://jira.mongodb.org/browse/EAI-249
- Note mentioning that you should include index definition for booster
-
Resolves #343

(EAI-249): Documentation improvement for Booster/filtering

---

packages/mongodb-chatbot-eval/src/Pipeline.ts
packages/mongodb-chatbot-eval/src/report/generateReportAndMetadata.ts

Jira: n/a
- Fix bug w/ generating report
- Catch errs in pipeline func
-
-

Eval bug fix

---

docs/docs/server/configure.md
packages/chatbot-server-mongodb-public/src/config.ts
packages/mongodb-chatbot-server/README.md
packages/mongodb-chatbot-server/src/routes/conversations/addMessageToConversation.test.ts
packages/mongodb-chatbot-server/src/routes/conversations/addMessageToConversation.ts
packages/mongodb-chatbot-server/src/routes/conversations/conversationsRouter.ts

Jira: https://jira.mongodb.org/browse/EAI-275
- Scope `DataStreamer` to route so there's no app-level collisions
- Test to see that can handle concurrent requests
- let's do some manual testing in staging when this is merged to further validate

(EAI-275): Scope data streamer to route to fix streaming err

---

examples/quick-start/packages/ui/src/index.css

Jira: n/a
- Remove light mode from quick start site. See below issue for more details.
Resolves https://github.com/mongodb/chatbot/issues/370

Remove light mode from quick start site

---

packages/mongodb-chatbot-verified-answers/example-verified-answers.yaml
packages/mongodb-chatbot-verified-answers/src/commands/import.ts
verified-answers.yaml

https://jira.mongodb.org/browse/EAI-289

(EAI-289): Add first verified answer

---

packages/chatbot-eval-mongodb-public/testCases/conversations.yml

Jira: https://jira.mongodb.org/browse/EAI-216
- Add evals based on reported user feedback
-
-

(EAI-216): add user feedback evals

---

packages/mongodb-chatbot-verified-answers/.env.example

- Remove unused env vars from the verified answers `.env.example` file

Verified Answers example should only show needed vars

---

.drone.yml
packages/chatbot-server-mongodb-public/README.md
packages/chatbot-server-mongodb-public/environments/dev-rel.yml

Jira: https://jira.mongodb.org/browse/EAI-299
- Create dedicated testing server for dev rel to generate responses with
- Uses GPT-4
- Uses separate DB in our staging cluster
- Server accessible @ https://dev-rel-generator.docs.staging.corp.mongodb.com/

(EAI-299): dedicated test server for dev rel

---

package-lock.json
packages/mongodb-chatbot-server/package.json
packages/mongodb-rag-core/package.json
packages/mongodb-rag-ingest/package.json

Jira: n/a
- Release core, ingest, and server packages
-
-

Releases for hackathon usage

---

package-lock.json
packages/mongodb-chatbot-server/src/processors/makeVerifiedAnswerGenerateUserPrompt.ts
packages/mongodb-chatbot-server/src/services/ConversationsService.ts
packages/mongodb-chatbot-ui/package.json
packages/mongodb-chatbot-ui/src/App.tsx
packages/mongodb-chatbot-ui/src/ConversationProvider.tsx
packages/mongodb-chatbot-ui/src/Message.tsx
packages/mongodb-chatbot-ui/src/createMessage.ts
packages/mongodb-chatbot-ui/src/services/conversations.test.ts
packages/mongodb-chatbot-ui/src/services/conversations.ts
packages/mongodb-chatbot-ui/src/useChatbot.tsx
packages/mongodb-chatbot-ui/src/useConversation.tsx

Jira: (EAI-306) [UI] Verified Answers in Chatbot UI
- Adds support for verified answers. Controlled by the server response's `metadata.verifiedAnswer` field
- ~This requires https://github.com/mongodb/leafygreen-ui/pull/2283 to be merged, published, and [integrated into Message.tsx](https://github.com/mongodb/chatbot/pull/386/files#diff-c544dbde4bc2252eaf8b40eb630cda5da53b323585d64986dd6c3c87f74e0c61) (see TODO comment).~

(EAI-306) [UI] Verified Answers in Chatbot UI

---

docs/docs/evaluation/command-reference.md
docs/docs/evaluation/configuration-reference.md
docs/docs/evaluation/index.md
docs/docs/evaluation/pipeline.md
docs/sidebars.ts

Jira: https://jira.mongodb.org/browse/EAI-233
- Initial doc set for the evaluation CLI
-

(EAI-233): Evaluation CLI docs expansion

---

.drone.yml
package-lock.json
packages/chatbot-eval-mongodb-public/use_cases.md
packages/ingest-mongodb-public/.env.example
packages/ingest-mongodb-public/environments/staging.yml
packages/ingest-mongodb-public/package.json
packages/ingest-mongodb-public/src/coachGtm.config.ts
packages/ingest-mongodb-public/src/sources/MongoDbDotComDataSource.test.ts
packages/ingest-mongodb-public/src/sources/MongoDbDotComDataSource.ts

Jira: https://jira.mongodb.org/browse/EAI-337
- Ingest mongodb.com CMS data
- new ingest for CoachGTM
- Deploy CoachGTM ingest to k8s cron
-

(EAI-337): CoachGTM ingest mongodb.com CMS

---

packages/ingest-mongodb-public/src/sources/MongoDbDotComDataSource.ts

Fix lint error & warnings

---

packages/ingest-mongodb-public/environments/staging.yml

Jira: n/a
- point the cron for coachgtm to the correct cluster
-
-

fix cluster secret

---

examples/quick-start/package-lock.json

Jira: n/a
- Update package-lock.json of quick start to include fix from #425 
-

Update quickstart lock

---

README.md
docs/docs/index.md

Jira: n/a
- Add bit of documentation noting that framework good for prototypes but also extensible to production
-
- Feel free to wordsmith @nlarew

Framing how to use framework

---

packages/mongodb-artifact-generator/context/release-notes/atlas-cli-releaseInfo.yaml
packages/mongodb-artifact-generator/src/ArtifactGeneratorEnvVars.ts
packages/mongodb-artifact-generator/src/Config.ts
packages/mongodb-artifact-generator/src/chat/index.ts
packages/mongodb-artifact-generator/src/chat/makeClassifier.test.ts
packages/mongodb-artifact-generator/src/chat/makeClassifier.ts
packages/mongodb-artifact-generator/src/chat/makeGenerateChatCompletion.ts
packages/mongodb-artifact-generator/src/commands/generateReleaseNotes.ts
packages/mongodb-artifact-generator/src/release-notes/classifyChangelog.ts
packages/mongodb-artifact-generator/src/release-notes/classifyChangelogAudience.ts
packages/mongodb-artifact-generator/src/release-notes/classifyChangelogScope.ts
packages/mongodb-artifact-generator/src/release-notes/createChangelog.ts
packages/mongodb-artifact-generator/src/release-notes/jira.ts
packages/mongodb-artifact-generator/src/release-notes/projects.ts
packages/mongodb-artifact-generator/src/release-notes/summarizeReleaseArtifacts.ts
packages/mongodb-artifact-generator/src/release-notes/utils.ts
packages/mongodb-artifact-generator/src/standardConfig.ts
packages/mongodb-artifact-generator/src/utils.ts
packages/mongodb-artifact-generator/tsconfig.json

Jira: (EAI-350) POC - Synthesize a Changelog

(EAI-350) POC - Synthesize a Changelog

---

docs/docs/ingest/configuration-reference.md
docs/docs/mongodb.md
docs/docs/server/find-faqs.md
docs/docs/server/verified-answers.md
docs/sidebars.ts
packages/mongodb-rag-core/src/VerifiedAnswer.ts

Jira: (EAI-263) Document verified answers
- Adds docs for verified answers & FAQ Finder

(EAI-263) Document verified answers

---

packages/mongodb-rag-core/src/EmbeddedContent.ts
packages/mongodb-rag-core/src/MongoDbEmbeddedContentStore.test.ts
packages/mongodb-rag-core/src/MongoDbEmbeddedContentStore.ts
packages/mongodb-rag-core/src/MongoDbPageStore.test.ts
packages/mongodb-rag-core/src/MongoDbPageStore.ts
packages/mongodb-rag-core/src/Page.ts

Jira: (EAI-403) configurable collection name for EmbeddedContentStore & PageStore

(EAI-403) configurable collection name for EmbeddedContentStore & PageStore

---

package-lock.json
packages/chatbot-eval-mongodb-public/.env.example
packages/chatbot-eval-mongodb-public/package.json
packages/chatbot-eval-mongodb-public/src/braintrust/evaluateLlmDiscoveryData.ts
packages/chatbot-eval-mongodb-public/src/braintrust/evaluateQuizQuestions.ts
packages/chatbot-eval-mongodb-public/src/braintrust/evaluateQuizQuestionsData.ts
packages/chatbot-eval-mongodb-public/src/braintrust/evaluateRagConversations.ts
packages/chatbot-eval-mongodb-public/src/braintrust/evaluateRagConversationsData.ts
packages/chatbot-eval-mongodb-public/src/braintrust/evaluateRagConversationsReferenceFree.ts
packages/chatbot-eval-mongodb-public/src/braintrust/evaluateRegexMatch.ts
packages/chatbot-eval-mongodb-public/src/braintrust/sample.eval.ts
packages/chatbot-eval-mongodb-public/src/braintrust/utils.ts
packages/model-eval/src/pipelines/quizEval.ts
packages/model-eval/src/quizEval.config.ts
packages/model-eval/src/radiantModels.ts
packages/mongodb-chatbot-evaluation/src/evaluate/evaluateQuizQuestionAnswerCorrectness.test.ts
packages/mongodb-chatbot-evaluation/src/evaluate/evaluateQuizQuestionAnswerCorrectness.ts
packages/mongodb-chatbot-evaluation/src/generate/GeneratedDataStore.ts
packages/mongodb-chatbot-evaluation/src/generate/generateLlmQuizQuestionAnswer.test.ts
packages/mongodb-chatbot-evaluation/src/generate/generateLlmQuizQuestionAnswer.ts

- Refactor quiz question eval to use more few shots + make the few shot user/assistant message based.
-  Built on top of the braintrust assessment branch (PR #450). merging this in so dont need to merge the braintrust PR
-

Quiz question Few shot as messages

---

package-lock.json
package.json
packages/chatbot-eval-mongodb-public/package.json
packages/chatbot-eval-mongodb-public/src/autoblocks/evaluateRagConversationsData.ts
packages/chatbot-eval-mongodb-public/src/autoblocks/evaluateRagConversationsReferenceFree.ts
packages/chatbot-eval-mongodb-public/src/autoblocks/sample.ts
packages/chatbot-eval-mongodb-public/src/braintrust/evaluateRagConversationsReferenceFree.ts

Jira: https://jira.mongodb.org/browse/EAI-469
-
-
-

(EAI-469): Autoblocks assessment

---

package-lock.json
packages/mongodb-chatbot-ui/package.json

Jira: (EAI-470) [UI] Fix dark mode sparkle color on ChatTrigger
- Bumps LG version to get the latest component
The sparkle icon is now the proper color in dark mode! 🎉

(EAI-470) [UI] Fix dark mode sparkle color on ChatTrigger

---

package-lock.json
packages/chatbot-eval-mongodb-public/.env.example
packages/chatbot-eval-mongodb-public/package.json
packages/chatbot-eval-mongodb-public/src/langfuse/evaluateLlmDiscoveryData.ts
packages/chatbot-eval-mongodb-public/src/langfuse/evaluateRegexMatch.ts

Jira: https://jira.mongodb.org/browse/EAI-477
- quick look at using langfuse for evals
-
-

(EAI-477): Langfuse assessment

---

packages/ingest-mongodb-public/.env.example
packages/ingest-mongodb-public/package.json
packages/ingest-mongodb-public/src/meta.config.ts

Jira: n/a
- Config + script to get MongoDB meta docs (https://www.mongodb.com/docs/meta/)
- For creating writing copilot(s)

Config + script to get MongoDB meta docs

---

package-lock.json
packages/benchmarks/package.json
packages/benchmarks/src/braintrust/evaluateQuizQuestions.ts
packages/benchmarks/src/braintrust/evaluateRegexMatch.ts
packages/benchmarks/src/braintrust/utils.ts
packages/benchmarks/src/discovery.config.ts
packages/benchmarks/src/makeRadiantChatLlm.ts
packages/benchmarks/src/pipelines/discoveryEvalToBraintrust.ts
packages/benchmarks/src/pipelines/quizEval.ts
packages/benchmarks/src/pipelines/quizEvalToBraintrust.ts
packages/benchmarks/src/quizEval.config.ts
packages/benchmarks/src/radiantModels.ts
packages/mongodb-chatbot-evaluation/src/Pipeline.test.ts
packages/mongodb-chatbot-evaluation/src/Pipeline.ts
packages/mongodb-chatbot-evaluation/src/evaluate/evaluateQuizQuestionAnswerCorrectness.test.ts
packages/mongodb-chatbot-evaluation/src/evaluate/evaluateQuizQuestionAnswerCorrectness.ts
packages/mongodb-chatbot-evaluation/src/generate/GeneratedDataStore.ts
packages/mongodb-chatbot-evaluation/src/generate/generateLlmConversationData.test.ts
packages/mongodb-chatbot-evaluation/src/generate/generateLlmQuizQuestionAnswer.test.ts
packages/mongodb-chatbot-evaluation/src/generate/generateLlmQuizQuestionAnswer.ts
packages/mongodb-rag-core/src/LangchainChatLlm.test.ts

Jira:
- https://jira.mongodb.org/browse/EAI-394
- https://jira.mongodb.org/browse/EAI-395
-

Rerun benchmarks with braintrust + more models

---

examples/quick-start/packages/server/src/index.ts

GitHub issue: https://github.com/mongodb/chatbot/issues/476
- Changed the return type of makeUserMessage to reflect the type definition of MakeUserMessageFunc
- First PR on this repo. Let me know if additional task is needed

ISSUES-476 makeUserMessage function response type

---

package-lock.json
packages/chatbot-server-mongodb-public/environments/production.yml
packages/chatbot-server-mongodb-public/package.json

Jira: https://jira.mongodb.org/browse/EAI-490
- deploy new server version
- fix prod k8s variable
-

(EAI-490): Deploy server to prod with upgraded main responder LLM

---

packages/mongodb-chatbot-ui/src/index.tsx
packages/mongodb-chatbot-ui/src/services/conversations.ts

Adds some missing exports for the UI package

add missing exports

---

package-lock.json
packages/chatbot-server-mongodb-public/package.json

Jira: https://jira.mongodb.org/browse/EAI-500
- See https://github.com/mongodb/chatbot/releases/tag/chatbot-server-mongodb-public-v0.7.0
-
-

(EAI-500): Release chatbot-server-mongodb-public v0.7.0

---

package-lock.json
packages/chatbot-server-mongodb-public/package.json

Jira: https://jira.mongodb.org/browse/EAI-492
-
-
-

(EAI-492): Release chatbot-server-mongodb-public v0.8.0

---

packages/ingest-mongodb-public/src/sources/snooty.ts

Jira: https://jira.mongodb.org/browse/EAI-530
- removed Datalake, device SDK, app-services
-
- removing app-services completely now because of an up-stream issue, a subset of app-services will be added later

remove Datalake, Device SDK, app-services

---

package-lock.json
packages/chatbot-server-mongodb-public/package.json

Jira: https://jira.mongodb.org/browse/EAI-515
- see release https://github.com/mongodb/chatbot/releases/tag/chatbot-server-mongodb-public-v0.9.0
-

(EAI-515): Release chatbot-server-mongodb-public v0.9.0

---

package-lock.json
packages/benchmarks/package.json
packages/benchmarks/src/textToDriver/DatabaseMetadata.ts
packages/benchmarks/src/textToDriver/generateDriverCode/extractDeterministicSampleOfDocuments.test.ts
packages/benchmarks/src/textToDriver/generateDriverCode/extractDeterministicSampleOfDocuments.ts
packages/benchmarks/src/textToDriver/generateDriverCode/index.ts
packages/benchmarks/src/textToDriver/generateDriverCode/languagePrompts/FewShotExample.ts
packages/benchmarks/src/textToDriver/generateDriverCode/languagePrompts/index.ts
packages/benchmarks/src/textToDriver/generateDriverCode/languagePrompts/nodeJs.ts
packages/benchmarks/src/textToDriver/generateDriverCode/makeGenerateDriverCode.test.ts
packages/benchmarks/src/textToDriver/generateDriverCode/makeGenerateDriverCode.ts
packages/benchmarks/src/textToDriver/generateDriverCode/makeTextToDriverPrompt.test.ts
packages/benchmarks/src/textToDriver/generateDriverCode/makeTextToDriverPrompt.ts

Jira: https://jira.mongodb.org/browse/EAI-535
- I suspect that the prompting will require updates once we start running the models on the data with it. But I think this is a good starting point from which we can update the prompt strings as needed.

(EAI-535): Code to generate query from prompt

---

docs/docs/ui.md
packages/mongodb-chatbot-ui/src/App.tsx
packages/mongodb-chatbot-ui/src/HotkeyTrigger.tsx
packages/mongodb-chatbot-ui/src/index.tsx

Jira: (EAI-543) [UI] Create HotkeyTrigger
- You can use this to open the chatbot with a user-defined hotkey

(EAI-543) [UI] Create HotkeyTrigger

---

verified-answers.yaml

Jira: https://jira.mongodb.org/browse/EAI-548
- Add initial MDBU verified answers
-
- Taken from #s 48 and 49 on https://docs.google.com/spreadsheets/d/1hC7mfhEiZhWqcZuyPfxdcLyOkxjq3HyVbdpOLH9qys4/edit?gid=0#gid=0
- Slightly modified text for clarity

(EAI-548):Add initial MDBU VAs

---

mongodb-uni/learning-paths/atlas-vector-search.md

Update RAG title and link

---

packages/mongodb-chatbot-server/src/processors/makeVerifiedAnswerGenerateUserPrompt.test.ts
packages/mongodb-chatbot-server/src/processors/makeVerifiedAnswerGenerateUserPrompt.ts
packages/mongodb-chatbot-server/src/routes/generateResponse.test.ts
packages/mongodb-chatbot-server/src/routes/generateResponse.ts

- Support streaming static message references
- Return references from verified answers user message
-

Fix: stream static msg references

---

packages/chatbot-server-mongodb-public/.env.example
packages/chatbot-server-mongodb-public/src/systemPrompt.ts

Jira: https://jira.mongodb.org/browse/EAI-570
- In the system prompt, have it not suggest further queries if there are no results. 
- Braintrust evals https://www.braintrust.dev/app/mdb-test/p/mongodb-chatbot-conversations/experiments/mongodb-chatbot-latest-165adb41
- note that this is using gpt-4o-mini as the judge LLM instead of gpt-4o b/c we were hitting token rate limits. this makes it hard to apples-to-apples compare the results.

(EAI-570): Update system prompt for no suggested queries 

---

package-lock.json
packages/mongodb-chatbot-ui/package.json
packages/mongodb-chatbot-ui/src/App.tsx
packages/mongodb-chatbot-ui/src/ChatWindow.tsx
packages/mongodb-chatbot-ui/src/Chatbot.tsx
packages/mongodb-chatbot-ui/src/HotkeyContext.tsx
packages/mongodb-chatbot-ui/src/HotkeyTrigger.tsx
packages/mongodb-chatbot-ui/src/InputBar.tsx
packages/mongodb-chatbot-ui/vite.config.component.ts

Jira: (EAI-565) [UI] Add HotkeyContext + connect HotkeyTrigger to placeholder
- The hotkey indicator in the InputBar now shows conditionally based on the presence of a `HotkeyTrigger`

(EAI-565) [UI] Add HotkeyContext + connect HotkeyTrigger to placeholder

---

packages/chatbot-server-mongodb-public/src/processors/userMessageMongoDbGuardrail.eval.ts
packages/chatbot-server-mongodb-public/src/processors/userMessageMongoDbGuardrail.ts

Jira: https://jira.mongodb.org/browse/EAI-564
- Update user message guardrail to allow general programming questions
- Add evaluations for new behavior
- Eval run - https://www.braintrust.dev/app/mdb-test/p/user-message-guardrail/experiments/gpt-4o-mini-9101efa0 (no regression)

(EAI-564): Widen guardrail prompt for general programming questions

---

packages/mongodb-chatbot-ui/src/ConversationProvider.tsx
packages/mongodb-chatbot-ui/src/useConversation.tsx

Jira: (EAI-575) [UI] Message Metadata Merging
- Adds `updateMessageMetadata` method & uses it in place of `setMessageMetadata`

(EAI-575) [UI] Message Metadata Merging

---

package-lock.json
packages/ingest-mongodb-public/package.json

Jira: https://jira.mongodb.org/browse/EAI-418
-
-
-

Release ingest-mongodb-public v0.7.0

---

packages/chatbot-server-mongodb-public/src/config.ts

Jira: n/a
- fix server bug where verified answers not using the correct embedding model for embedded content store after #559 
-
-

fix: use the correct embedding model for verified answers

---

packages/ingest-mongodb-public/src/sources/snootySources.ts

Jira: (EAI-583) [Ingest] Add MongoDB IntelliJ Plugin docs
- Ingest new Intellij Plugin docs

(EAI-583) [Ingest] Add MongoDB IntelliJ Plugin docs

---

packages/ingest-mongodb-public/package.json

Jira: n/a
- Fix npm scripts to use `ingest <embed|pages> update` 
-
- Done b/c of changes in #556

update ingest CLI calls to use `ingest <command> update` syntax

---

.drone.yml
packages/ingest-mongodb-public/environments/coachGtm.staging.yml
packages/ingest-mongodb-public/environments/staging.yml

Jira: https://jira.mongodb.org/browse/EAI-368
- alerts to sergio's team `sit@mongodb.com`
- [had to create a new cronjob file for this :(](https://github.com/10gen/helm-charts/blob/master/charts/cronjobs/README.md#cronjobs:~:text=NOTE%20image%20and%20all%20default*%20parameters%20except%20defaultAlerts%20can%20be%20overriden%20per%20cronJob%20definition.)

(EAI-368): Alerts on cronjob failure to sergio

---

packages/chatbot-server-mongodb-public/environments/staging.yml

Jira: n/a
- fix bug that was causing staging server to not deploy w/ secrets 😬 
-
-

fix staging env indent

---

packages/ingest-mongodb-public/ingestion_guide.md

Jira: n/a
- Data ingestion guide for when we want to add new data sources
-
-

Ingestion guide

---

packages/mongodb-artifact-generator/context/release-notes/mongosh-releaseInfo.yaml

Jira: (EAI-651) Source mongosh Release Artifacts

(EAI-651) Source mongosh Release Artifacts

---

packages/chatbot-server-mongodb-public/environments/production.yml

Jira: https://jira.mongodb.org/browse/EAI-644
- Add Braintrust and slack secrets to prod
- Increase the prod resource usage b/c of recent errors to emails about approaching resource limits
- Also added the relevant secrets to our k8s env secrets `docs-chatbot-prod` via CLI (not in PR)

update prod env

---

packages/mongodb-chatbot-server/src/routes/conversations/addMessageToConversation.ts

Jira: n/a
- Send less tracing data to Braintrust. Removes much tracing data such as embeddings, links, etc from previous messages in the conversation. This makes the logs in Braintrust send quicker, use less memory, and (most importantly for us) are more readable
-
-

Reduce tracing data set to Braintrust

---

packages/chatbot-server-mongodb-public/src/tracing/postCommentToSlack.ts

Jira: n/a
- Fix bug where negative comments weren't being sent to Slack
-
-

bug fix: Post negative comments to slack

---

packages/ingest-mongodb-public/src/sources/snootySources.ts

Jira: (EAI-877) Ingest docs for Atlas k8s Operator, Kotlin Sync, Django
Approved by content team in this thread https://mongodb.slack.com/archives/C0339UHK56H/p1740423296768849

(EAI-877) Ingest docs for Atlas k8s Operator, Kotlin Sync, Django

---

examples/quick-start/package-lock.json
examples/quick-start/packages/ingest/package.json
examples/quick-start/packages/ingest/src/ingest.config.ts

Jira: n/a
- Update `mongodb-rag-core` version in quick start to fix import issue
- Also remove unused import (not related to the import issue)
- Resolves #630

[quick start] Fix ingest import issue

---

packages/chatbot-server-mongodb-public/src/config.ts
packages/chatbot-server-mongodb-public/src/tracing/postCommentToSlack.test.ts
packages/chatbot-server-mongodb-public/src/tracing/postCommentToSlack.ts
packages/chatbot-server-mongodb-public/src/tracing/routesUpdateTraceHandlers.ts

Jira:
- (EAI-887) More prominent indication of verified answers in Slack
- (EAI-890) Have slack message link directly to Braintrust trace

Update slack feedback message

---

packages/chatbot-server-mongodb-public/src/config.ts
packages/mongodb-chatbot-server/src/routes/conversations/addMessageToConversation.test.ts
packages/mongodb-chatbot-server/src/routes/conversations/conversationsRouter.ts

Jira: (EAI-848) Store User-Agent in metadata
- Saves `customData.userAgent` for conversations & messages
- Cleans up our existing `customData` code

(EAI-848) Store User-Agent in metadata

---

package-lock.json
package.json
packages/scripts/package.json
packages/scripts/src/main/listSlackMessagesMain.ts
packages/scripts/src/main/removeSlackMessageMain.ts

List messages script is not functional because Quokkabot lacks the required scopes. If we ever get them added then the script will just work.

Scripts to list (non-functional) and delete slack messages

---

packages/ingest-mongodb-public/src/sources/snootySources.ts

Jira: https://jira.mongodb.org/browse/EAI-937
- guides data source removed
- /guides has been sunset - https://mongodb.slack.com/archives/C018UTGP23T/p1743545217884599

rm guides data source

---

package-lock.json
packages/ingest-mongodb-public/package.json

Release - https://github.com/mongodb/chatbot/releases/tag/untagged-969281fa6e16751f5377

Release ingest-mongodb-public v0.12.1

---

packages/chatbot-server-mongodb-public/environments/production.yml
packages/chatbot-server-mongodb-public/environments/staging.yml

Jira: (EAI-981) Add Segment Write Key to server envs
I already defined the secrets in k8s via `kubectl`

(EAI-981) Add Segment Write Key to server envs

---

packages/chatbot-server-mongodb-public/src/config.ts
packages/chatbot-server-mongodb-public/src/middleware/redactConnectionUri.test.ts
packages/chatbot-server-mongodb-public/src/middleware/redactConnectionUri.ts

Jira: https://jira.mongodb.org/browse/EAI-929
- Redact MongoDB connection URIs on incoming requests
-
-

(EAI-929): Redact connection URIs from messages

---

packages/ingest-mongodb-public/environments/staging.yml
packages/ingest-mongodb-public/package.json
packages/ingest-mongodb-public/src/docsWithLinks.config.ts
packages/ingest-mongodb-public/src/sources/snooty/SnootyDataSource.ts
packages/ingest-mongodb-public/src/sources/snooty/SnootyProjectsInfo.ts
packages/ingest-mongodb-public/src/sources/snooty/renderSnootyTable.ts
packages/ingest-mongodb-public/src/sources/snooty/snootyAstToMd.test.ts
packages/ingest-mongodb-public/src/sources/snooty/snootyAstToMd.ts
packages/ingest-mongodb-public/src/sources/snootySources.ts
packages/ingest-mongodb-public/testData/samplePageWithExternalLinks.json
packages/ingest-mongodb-public/testData/samplePageWithInternalLinks.json
packages/ingest-mongodb-public/testData/samplePageWithInternalLinksNoFragment.json
packages/ingest-mongodb-public/testData/samplePageWithIntersphinx.json

Jira: https://jira.mongodb.org/browse/EAI-1000
- Add config to docs ingest to include links and anchors
- Create a new ingest job for the docs content with links
- No impact on current ingest job.
- This is to support including links in llms.txt files

(EAI-1000): Ingest docs content with links

---

packages/datasets/src/pageDataset/loadPageDataset.test.ts
packages/datasets/src/pageDataset/loadPageDataset.ts

Jira: https://jira.mongodb.org/browse/EAI-922
- matching on current versions
- added test case for current version
- modified some existing tests that were false positives
-

(EAI-922) ensure only current version on hugging face dataset

---

verified-answers.yaml

Jira: https://jira.mongodb.org/browse/EAI-1021
- Add verified answer about pricing
-
-

(EAI-1021): Add pricing verified answer

---

packages/ingest-mongodb-public/maxxPrompts/atlasStreamProcessing.md
packages/ingest-mongodb-public/src/bin/makeAtlasCliMaxxPrompt.ts
packages/ingest-mongodb-public/src/bin/makeAtlasStreamProcessingPrompt.ts
packages/ingest-mongodb-public/src/bin/makeAtlasVectorSearchMaxxPrompt.ts
packages/ingest-mongodb-public/src/bin/makeKotlinDriverMaxxPrompt.ts

stream processing

---

packages/mcp/src/helpers/resourceHandler.ts
packages/mcp/src/helpers/toolHandler.ts
packages/mcp/src/index.ts

Add the following tools:
- list-guides
- use-guides

Create basic MCP tools (list docs guides, view docs guides)

---

package-lock.json
packages/mcp/package.json
packages/mcp/src/handlers/resources.ts
packages/mcp/src/index.ts

- Pass config vars via flags 
This'd look like:
```
node /Users/ben.p/projects/chatbot/packages/mcp/build/index.js
\ --openAiApiKey <API_KEY> 
\ --openAiEndpoint https://docs-ai-chatbot-useast2resource-sandbox.openai.azure.com/ 
\ --mongoDbConnectionUri mongodb+srv://<USER>:<PASS>@docs-chatbot-dev.kibrp71.mongodb.net/ 
\ --mongoDbDatabaseName docs-chatbot-dev
```
-

Env as args

---

packages/mcp/static/prompts/get-started.md

Add get started prompt

---

packages/chatbot-server-mongodb-public/src/config.ts
packages/mcp/src/handlers/tools.ts
packages/mcp/src/index.ts
packages/mcp/src/logPath.ts

- fix search and pages endpoints. must have chatbot-server-mongodb-public running at localhost:3000 to work
- no longer need to pass the env vars 
-

Fix search

---

packages/mcp/static/resources/vector-search.md

Pre demo - add voyage stuff

---

packages/scripts/README.md

- update readme and trigger build
-
-

Update scripts README.md

---

.drone.yml
scripts-service.dockerfile

- fix issue causing scripts to not deploy. wasn't building an introduced local dependency on `chatbot-server-mongodb-public`, causing failure in drone.
- see this drone for example failure: https://drone.corp.mongodb.com/mongodb/chatbot/5405/2/2
-
-

fix script deployment problem

---

CONTRIBUTING.md

- Clarify process for raising PRs, it's slightly different for mongo employees

Minor edits to CONTRIBUTING.md

---

package-lock.json
packages/chatbot-server-mongodb-public/package.json
packages/chatbot-server-mongodb-public/src/tracing/segment.test.ts
packages/chatbot-server-mongodb-public/src/tracing/segment.ts

Jira: (EAI-1061) Throw & log descriptive errors for Segment tracing

(EAI-1061) Better error handling & logging for segment events

---

packages/ingest-mongodb-public/src/sources/snooty/snootyAstToOpenApiSpec.ts
packages/ingest-mongodb-public/testData/remoteOpenApiSpecPage.json

Jira: https://jira.mongodb.org/browse/EAI-1071
- Fix broken ingestion of Atlas OpenAPI spec.
- See ticket for more context
- Updated sample data to match current Atlas OpenAPI spec page
-

(EAI-1071): Fix broken Atlas OpenAPI ingest

---

packages/mongodb-chatbot-ui/src/App.tsx
packages/mongodb-chatbot-ui/src/ChatMessageFeed.tsx
packages/mongodb-chatbot-ui/src/Chatbot.tsx
packages/mongodb-chatbot-ui/src/InputBarTrigger.tsx
packages/mongodb-chatbot-ui/src/Message.tsx
packages/mongodb-chatbot-ui/src/useChatbot.tsx
packages/mongodb-chatbot-ui/src/useTextInputTrigger.ts

Jira: (EAI-1070) [UI] Add client handler for suggested prompt click
- New `Chatbot` prop that runs a callback when you click a suggested prompt

Add client handler for suggested prompt click

---

packages/mongodb-chatbot-ui/src/MongoDbLegal.tsx

Jira: (EAI-1081) Add link to FAQ doc in Chatbot message feed
- Add link to Data & Usage docs page to our legal disclaimer text

(EAI-1081) Add link to FAQ doc in Chatbot message feed

---

verified-answers.yaml

Jira: https://jira.mongodb.org/browse/EAI-885
- Adds 2 docs references to one of our university VAs in case the user prefers to visit the docs instead of university

(EAI-885) Improve references on GenAI University verified answer

---

packages/chatbot-server-mongodb-public/src/config.ts
packages/chatbot-server-mongodb-public/src/tracing/getLlmAsAJudgeScores.ts

Jira: https://jira.mongodb.org/browse/EAI-1092
- title & update some braintrust trace names

(EAI-1092) Fix tracing scores returning null

---

packages/chatbot-server-mongodb-public/src/tracing/extractTracingData.test.ts
packages/chatbot-server-mongodb-public/src/tracing/extractTracingData.ts
packages/chatbot-server-mongodb-public/src/tracing/routesUpdateTraceHandlers.ts
packages/chatbot-server-mongodb-public/src/tracing/scrubbedMessages/analyzeMessage.ts
packages/chatbot-server-mongodb-public/src/tracing/scrubbedMessages/makeScrubbedMessagesFromTracingData.ts
packages/chatbot-server-mongodb-public/src/tracing/tagify.ts
packages/mongodb-rag-core/src/mongoDbMetadata/classifyMetadata.eval.ts
packages/mongodb-rag-core/src/mongoDbMetadata/classifyMetadata.ts

Jira: 
- https://jira.mongodb.org/browse/EAI-1104
- https://jira.mongodb.org/browse/EAI-1094
- compute tracing metadata in update trace route
- better naming on traces
- Scrub messages before extracting keywords (EAI-1094)
-

(EAI-1104 and EAI-1094): metadata in tracing, scrub PII before keywords

---

packages/scripts/environments/production.yml
packages/scripts/environments/staging.yml

Jira: https://jira.mongodb.org/browse/EAI-1053
- Fixes invalid input type for `command`, should be an array

(EAI-1053) Fixing new script deploy

---

packages/mongodb-chatbot-server/src/routes/responses/responsesRouter.test.ts
packages/mongodb-chatbot-server/src/routes/responses/responsesRouter.ts
packages/mongodb-chatbot-server/src/test/testHelpers.ts

- implement rate limit middleware
- Ensures standard errors by overriding the handler for rate limit middleware

Add rate limiting to responses api

---

packages/chatbot-server-mongodb-public/src/tracing/routesUpdateTraceHandlers.ts
packages/mongodb-chatbot-server/src/routes/conversations/addMessageToConversation.ts

Jira: (EAI-1082) Fix missing scrubbed messages
- Runs "update trace handlers" for both streamed and non-streamed responses (previously only ran for streamed)

(EAI-1082) Fix missing scrubbed messages

---

package.json

Jira: https://jira.mongodb.org/browse/EAI-1119
- script missing from root package.json, not running in cron
-
-

add script to root package.json

---

README.md

Jira: n/a
- Less talk of framework deprecation in README
-
- per slack convo

Less talk of framework deprecation in README

---

packages/ingest-mongodb-public/src/sources/mongodbDotCom/webSources.ts

Jira: https://jira.mongodb.org/browse/EAI-1099
- Ingest (scrape) voyage AI blog posts
- Linting

(EAI-1099) Ingest voyageAI blog posts

---

packages/ingest-mongodb-public/src/sources/mongodbDotCom/webSources.ts

Jira: https://jira.mongodb.org/browse/EAI-1138
- Ingest instructor-led training schedule page 
- to ingest ILT course detail PDFs in a separate PR

(EAI-1138) Ingest ILT schedule

---

.prompts/braintrut-loop.md
packages/chatbot-server-mongodb-public/src/processors/mongoDbInputGuardrail.eval.ts
packages/chatbot-server-mongodb-public/src/processors/mongoDbInputGuardrail.ts

Jira: n/a
- Add prompt to repo to use Braintrust MCP for prompt refinement.
- Update the guardrail based on the prompt workflow
-

Braintrust Loop prompt

---

package-lock.json
packages/chatbot-server-mongodb-public/package.json
packages/chatbot-server-mongodb-public/src/config.ts
packages/chatbot-server-mongodb-public/src/processors/generateResponseWithSearchTool.test.ts
packages/chatbot-server-mongodb-public/src/processors/generateResponseWithSearchTool.ts
packages/chatbot-server-mongodb-public/src/responsesApi.test.ts
packages/chatbot-server-mongodb-public/src/test/testHelpers.ts
packages/mongodb-chatbot-server/src/processors/GenerateResponse.ts
packages/mongodb-chatbot-server/src/processors/makeDefaultReferenceLinks.ts
packages/mongodb-chatbot-server/src/routes/responses/createResponse.test.ts
packages/mongodb-chatbot-server/src/routes/responses/createResponse.ts
packages/mongodb-chatbot-server/src/routes/responses/errors.ts
packages/mongodb-chatbot-server/src/routes/responses/responsesRouter.test.ts
packages/mongodb-chatbot-server/src/test/testConfig.ts
packages/mongodb-chatbot-server/src/test/testHelpers.ts
packages/mongodb-rag-core/src/DataStreamer.test.ts
packages/mongodb-rag-core/src/DataStreamer.ts

Jira: https://jira.mongodb.org/browse/EAI-125
- Configure the public chat server to use the new responses streaming API
-

Implement generate new response

---

verified-answers.yaml

Jira: (EAI-1177) Add verified answers for AI chatbot

(EAI-1177) Add verified answers for AI chatbot

---

packages/mongodb-chatbot-ui/src/App.tsx
packages/mongodb-chatbot-ui/src/ChatMessageFeed.tsx
packages/mongodb-chatbot-ui/src/ChatWindow.tsx
packages/mongodb-chatbot-ui/src/ChatbotView.tsx
packages/mongodb-chatbot-ui/src/DevCenterChatbot.tsx
packages/mongodb-chatbot-ui/src/Message.tsx
packages/mongodb-chatbot-ui/src/MessageRating.tsx

Jira: (EAI-1175) Add slot to messages below message rating
- Adds `View.messageBottomContent` prop to slot in arbitrary react nodes at the bottom of each message
- Will be used by forum team for links out to 3PF

(EAI-1175) Add slot to messages below message rating

---

packages/mongodb-chatbot-server/src/app.ts

Jira: https://jira.mongodb.org/browse/EAI-1191
- more robust CORS error handling
- always return 403 when CORS throws an error

more robust CORS error handling

---

packages/chatbot-server-mongodb-public/src/responsesApi.test.ts
packages/mongodb-chatbot-server/src/routes/responses/createResponse.test.ts
packages/mongodb-chatbot-server/src/routes/responses/createResponse.ts

Jira: https://jira.mongodb.org/browse/EAI-1193
- allow input_text style content input:
```
content: [{ type: "input_text", text: "What is MongoDB?" }],
```

Responses api - allow input_text objects in input

---

packages/mongodb-chatbot-server/src/routes/conversations/commentMessage.test.ts
packages/mongodb-chatbot-server/src/routes/conversations/commentMessage.ts

Jira: https://jira.mongodb.org/browse/EAI-1196
- Tombstone comments with empty string if `storeMessageContent=false`
-
-

(EAI-1196): Tombstone comments if storeMessageContent=false

---

packages/mongodb-chatbot-server/src/routes/conversations/addMessageToConversation.test.ts
packages/mongodb-chatbot-server/src/routes/conversations/addMessageToConversation.ts
packages/mongodb-chatbot-server/src/routes/conversations/constants.ts
packages/mongodb-chatbot-server/src/routes/conversations/createConversation.ts
packages/mongodb-chatbot-server/src/routes/conversations/getConversation.test.ts
packages/mongodb-chatbot-server/src/routes/responses/createResponse.test.ts
packages/mongodb-chatbot-server/src/routes/responses/createResponse.ts
packages/mongodb-rag-core/src/conversations/ConversationsService.ts
packages/mongodb-rag-core/src/conversations/MongoDbConversations.test.ts
packages/mongodb-rag-core/src/conversations/MongoDbConversations.ts

Jira: https://jira.mongodb.org/browse/EAI-1200
- Add optional creationInterface property to conversation
- Add different options for different API interfaces 
-

(EAI-1200): Add optional creationInterface property to conversation

---

packages/chatbot-server-mongodb-public/src/processors/generateResponseWithTools.ts
packages/mongodb-chatbot-server/src/processors/makeVerifiedAnswerGenerateResponse.ts

Jira: https://jira.mongodb.org/browse/EAI-1205
- ensure item ids are set for response events

ensure item ids are set for response events

---

docs/docs/server/responses-api.md

Jira: n/a
Fixes a couple broken links to provide the correct relative paths
-

fix broken links to openapi spec

---

packages/chatbot-server-mongodb-public/environments/production.yml
packages/chatbot-server-mongodb-public/environments/staging.yml
packages/chatbot-server-mongodb-public/src/processors/mongoDbInputGuardrail.eval.ts
packages/chatbot-server-mongodb-public/src/processors/mongoDbInputGuardrail.ts

Jira: https://jira.mongodb.org/browse/EAI-1226
- Updates guardrail system prompt with instructions on handling custom system prompt and custom tools 
- Switches to gpt-4.1-mini for guardrail 
- [Braintrust summary of results for gpt-4.1-nano/mini](https://www.braintrust.dev/app/mongodb-education-ai/p/user-message-guardrail/experiments?ye=metric|llm_duration,metric|prompt_tokens,metric|completion_tokens,metric|total_tokens&search={%22filter%22:[%22id%2520%253D%2520%272121d63d-1ea4-4b73-9c52-697fc2d34179%27%2520OR%2520%250Aid%2520%253D%2520%2747285dbd-0c7c-4aa0-8a8a-5a3000799625%27%2520OR%2520%250Aid%2520%253D%2520%27d89f29d6-33c7-4a65-aa72-be3f2f7655b5%27%2520OR%2520%250Aid%2520%253D%2520%27a7ddde5a-b10b-4ba7-930f-302ca119de5c%27%2520OR%2520%250Aid%2520%253D%2520%27468ca2b6-cdb7-4b57-aadd-c …

(EAI-1226) Guardrail eval & refinement for custom system prompt and tools

---

packages/benchmarks/src/benchmarkModels.ts
packages/mongodb-rag-core/src/models/models.ts

Jira: https://jira.mongodb.org/browse/EAI-1263
- added models 
- added documentation about available models
-

(EAI-1263) add models
